import type { LucideIcon } from "lucide-react";
import {
  // Speed & Power
  Zap, ZapOff, Rocket, Flame, Gauge, Activity, TrendingUp, TrendingDown,
  Wind, Tornado, Timer, TimerOff, FastForward, Rewind, ChevronsRight, ChevronsLeft,
  ChevronsUp, ChevronsDown, ArrowBigUp, ArrowBigDown, ArrowBigRight, ArrowBigLeft,
  BarChart, BarChart2, BarChart3, BarChart4, LineChart, AreaChart,
  RefreshCw, RefreshCcw, RotateCw, RotateCcw, Repeat, Repeat2,
  Battery, BatteryCharging, BatteryFull, BatteryLow, BatteryMedium, BatteryWarning,
  SkipForward, SkipBack, ChevronRight, ChevronLeft, ChevronUp, ChevronDown,
  // Rank & Awards
  Crown, Trophy, Medal, Award, Star, StarHalf, StarOff,
  Diamond, Gem, Sparkles, Ribbon, BadgeCheck,
  BadgeAlert, BadgeDollarSign, BadgeInfo, BadgeMinus, BadgePlus, BadgeX,
  // Animals & Nature
  Snail, Turtle, Bug, Bird, Fish, Worm, Dog, Cat, Egg,
  Shell, Leaf, TreePine, Flower, Flower2, Sprout,
  Sun, Moon, Sunrise, Sunset, Rainbow, Snowflake, CloudRain, CloudLightning,
  CloudSnow, Cloud, Droplet, Droplets, Waves, Mountain, MountainSnow,
  // People & Emotions
  User, UserCheck, UserMinus, UserPlus, UserX, Users,
  Heart, HeartCrack, HeartHandshake, HeartOff, HeartPulse,
  Smile, Frown, Meh, Laugh, ThumbsUp, ThumbsDown,
  Baby, Ghost, Skull, PersonStanding,
  // Tech & Devices
  Code, Code2, Terminal, Monitor, Laptop, Tablet, Smartphone, Tv, Watch,
  Cpu, HardDrive, Server, Database, DatabaseBackup, DatabaseZap,
  Globe, Globe2, Wifi, WifiOff, Bluetooth, Radio, Plug, Unplug,
  Camera, Video, Image, Mic, MicOff, Speaker, Volume, Volume1, Volume2, VolumeX,
  Headphones, Keyboard, Mouse, Power, Binary, Network, Layers,
  // Security & Safety
  Shield, ShieldCheck, ShieldAlert, ShieldOff, ShieldX,
  Lock, LockOpen, LockKeyhole, Key, KeyRound, Eye, EyeOff, Fingerprint,
  AlertTriangle, AlertCircle, AlertOctagon, Scan, QrCode,
  // Finance & Business
  DollarSign, Euro, Bitcoin, CreditCard, Wallet, Coins, Banknote, Receipt,
  ShoppingCart, ShoppingBag, Store, Package, Tag, Tags, Percent,
  Scale, Calculator, PieChart, TrendingUp as TrendUp, HandCoins,
  // Communication
  MessageCircle, MessageSquare, Mail, MailOpen, Phone, PhoneCall,
  PhoneIncoming, PhoneOutgoing, PhoneMissed, PhoneOff, Send,
  Megaphone, Bell, BellDot, BellOff, BellPlus, BellRing,
  Share, Share2, Link, Link2, ExternalLink, Rss, Podcast, Forward, Reply,
  // Media & Entertainment
  Play, Pause, Music, Music2, Film, Tv2, Clapperboard,
  Disc, Disc2, Disc3, ListMusic, Radio as RadioIcon,
  BookOpen, Book, BookMarked, ScrollText,
  Gamepad, Gamepad2, Joystick, Dice1, Dice2, Dice3, Dice4, Dice5, Dice6,
  // Sports & Action
  Dumbbell, Target, Crosshair, Swords, Sword, Axe, Bomb, Flag, FlagOff,
  Move, MoveRight, MoveLeft, MoveUp, MoveDown, Navigation, Navigation2, Compass,
  // Symbols & Signs
  Infinity, Hash, AtSign, Asterisk, Plus, Minus, Divide,
  CheckCircle, CheckCircle2, XCircle, Circle, CircleDot, CirclePlus, CircleMinus,
  Triangle, Square, Pentagon, Hexagon, Octagon,
  Info, HelpCircle, Ban, Slash, Verified, Copyright,
  // World & Places
  Map as MapIcon, MapPin, Globe as GlobeWorld, Landmark, Home, Building, Building2,
  Hotel, School, Hospital, Plane, Car, Truck, Bike, Ship, Train, Bus,
  Sailboat, Tent, Castle,
  // Food & Life
  Coffee, Beer, Wine, Pizza, Apple, Cherry, Banana, IceCream2, Cookie,
  Cake, Croissant, Sandwich, Soup, Salad, IceCream, Donut,
  ChefHat, UtensilsCrossed, Utensils, CookingPot, Microwave, Refrigerator,
  // Shapes & Design
  Palette, Paintbrush, PaintBucket, Pipette, Eraser, Pencil, Pen, PenLine,
  Highlighter, Scissors, Crop, Wand, Wand2, Blend, Blocks,
  // Tools & Build
  Wrench, Hammer, Cog, Settings, Settings2, Sliders, SlidersHorizontal,
  FlaskConical, TestTube, TestTube2, Atom, Microscope, Telescope, Binoculars,
  // Misc
  Gift, PartyPopper, Sparkle, Lightbulb, LightbulbOff, Magnet,
  Anchor, Coffee as CoffeeMisc, Hourglass, Umbrella,
  Bookmark, BookmarkPlus, BookmarkCheck, BookmarkX,
  Paperclip, Clip, Pin, PinOff,
} from "lucide-react";

export interface IconEntry {
  key: string;
  Icon: LucideIcon;
  label: string;
  category: string;
}

export const ICON_CATEGORIES = [
  "All",
  "⚡ Speed & Power",
  "👑 Rank & Awards",
  "🐾 Animals & Nature",
  "👤 People & Emotions",
  "⚙️ Tech & Devices",
  "🔒 Security & Safety",
  "💰 Finance & Trade",
  "💬 Communication",
  "🎬 Media & Entertainment",
  "🏋️ Sports & Action",
  "🔣 Symbols & Signs",
  "🌍 World & Places",
  "🍕 Food & Life",
  "🎨 Design & Tools",
];

export const ICON_REGISTRY: IconEntry[] = [
  // ─── Speed & Power ─────────────────────────────────────────────────────────
  { key: "Zap",           Icon: Zap,           label: "Zap",          category: "⚡ Speed & Power" },
  { key: "ZapOff",        Icon: ZapOff,        label: "Zap Off",      category: "⚡ Speed & Power" },
  { key: "Rocket",        Icon: Rocket,        label: "Rocket",       category: "⚡ Speed & Power" },
  { key: "Flame",         Icon: Flame,         label: "Flame",        category: "⚡ Speed & Power" },
  { key: "Gauge",         Icon: Gauge,         label: "Gauge",        category: "⚡ Speed & Power" },
  { key: "Activity",      Icon: Activity,      label: "Activity",     category: "⚡ Speed & Power" },
  { key: "TrendingUp",    Icon: TrendingUp,    label: "Trending Up",  category: "⚡ Speed & Power" },
  { key: "TrendingDown",  Icon: TrendingDown,  label: "Trending Down",category: "⚡ Speed & Power" },
  { key: "Wind",          Icon: Wind,          label: "Wind",         category: "⚡ Speed & Power" },
  { key: "Tornado",       Icon: Tornado,       label: "Tornado",      category: "⚡ Speed & Power" },
  { key: "Timer",         Icon: Timer,         label: "Timer",        category: "⚡ Speed & Power" },
  { key: "TimerOff",      Icon: TimerOff,      label: "Timer Off",    category: "⚡ Speed & Power" },
  { key: "FastForward",   Icon: FastForward,   label: "Fast Forward", category: "⚡ Speed & Power" },
  { key: "Rewind",        Icon: Rewind,        label: "Rewind",       category: "⚡ Speed & Power" },
  { key: "ChevronsRight", Icon: ChevronsRight, label: "Chevrons Right", category: "⚡ Speed & Power" },
  { key: "ChevronsLeft",  Icon: ChevronsLeft,  label: "Chevrons Left",  category: "⚡ Speed & Power" },
  { key: "ChevronsUp",    Icon: ChevronsUp,    label: "Chevrons Up",    category: "⚡ Speed & Power" },
  { key: "ChevronsDown",  Icon: ChevronsDown,  label: "Chevrons Down",  category: "⚡ Speed & Power" },
  { key: "ArrowBigUp",    Icon: ArrowBigUp,    label: "Arrow Big Up",   category: "⚡ Speed & Power" },
  { key: "ArrowBigDown",  Icon: ArrowBigDown,  label: "Arrow Big Down", category: "⚡ Speed & Power" },
  { key: "ArrowBigRight", Icon: ArrowBigRight, label: "Arrow Big Right",category: "⚡ Speed & Power" },
  { key: "ArrowBigLeft",  Icon: ArrowBigLeft,  label: "Arrow Big Left", category: "⚡ Speed & Power" },
  { key: "BarChart",      Icon: BarChart,      label: "Bar Chart",    category: "⚡ Speed & Power" },
  { key: "BarChart2",     Icon: BarChart2,     label: "Bar Chart 2",  category: "⚡ Speed & Power" },
  { key: "BarChart3",     Icon: BarChart3,     label: "Bar Chart 3",  category: "⚡ Speed & Power" },
  { key: "BarChart4",     Icon: BarChart4,     label: "Bar Chart 4",  category: "⚡ Speed & Power" },
  { key: "LineChart",     Icon: LineChart,     label: "Line Chart",   category: "⚡ Speed & Power" },
  { key: "AreaChart",     Icon: AreaChart,     label: "Area Chart",   category: "⚡ Speed & Power" },
  { key: "RefreshCw",     Icon: RefreshCw,     label: "Refresh CW",   category: "⚡ Speed & Power" },
  { key: "RefreshCcw",    Icon: RefreshCcw,    label: "Refresh CCW",  category: "⚡ Speed & Power" },
  { key: "RotateCw",      Icon: RotateCw,      label: "Rotate CW",    category: "⚡ Speed & Power" },
  { key: "RotateCcw",     Icon: RotateCcw,     label: "Rotate CCW",   category: "⚡ Speed & Power" },
  { key: "Repeat",        Icon: Repeat,        label: "Repeat",       category: "⚡ Speed & Power" },
  { key: "Repeat2",       Icon: Repeat2,       label: "Repeat 2",     category: "⚡ Speed & Power" },
  { key: "Battery",       Icon: Battery,       label: "Battery",      category: "⚡ Speed & Power" },
  { key: "BatteryCharging",Icon: BatteryCharging,label: "Charging",   category: "⚡ Speed & Power" },
  { key: "BatteryFull",   Icon: BatteryFull,   label: "Battery Full", category: "⚡ Speed & Power" },
  { key: "BatteryLow",    Icon: BatteryLow,    label: "Battery Low",  category: "⚡ Speed & Power" },
  { key: "SkipForward",   Icon: SkipForward,   label: "Skip Forward", category: "⚡ Speed & Power" },
  { key: "SkipBack",      Icon: SkipBack,      label: "Skip Back",    category: "⚡ Speed & Power" },

  // ─── Rank & Awards ─────────────────────────────────────────────────────────
  { key: "Crown",          Icon: Crown,          label: "Crown",        category: "👑 Rank & Awards" },
  { key: "Trophy",         Icon: Trophy,         label: "Trophy",       category: "👑 Rank & Awards" },
  { key: "Medal",          Icon: Medal,          label: "Medal",        category: "👑 Rank & Awards" },
  { key: "Award",          Icon: Award,          label: "Award",        category: "👑 Rank & Awards" },
  { key: "Star",           Icon: Star,           label: "Star",         category: "👑 Rank & Awards" },
  { key: "StarHalf",       Icon: StarHalf,       label: "Star Half",    category: "👑 Rank & Awards" },
  { key: "StarOff",        Icon: StarOff,        label: "Star Off",     category: "👑 Rank & Awards" },
  { key: "Diamond",        Icon: Diamond,        label: "Diamond",      category: "👑 Rank & Awards" },
  { key: "Gem",            Icon: Gem,            label: "Gem",          category: "👑 Rank & Awards" },
  { key: "Sparkles",       Icon: Sparkles,       label: "Sparkles",     category: "👑 Rank & Awards" },
  { key: "Sparkle",        Icon: Sparkle,        label: "Sparkle",      category: "👑 Rank & Awards" },
  { key: "Ribbon",         Icon: Ribbon,         label: "Ribbon",       category: "👑 Rank & Awards" },
  { key: "BadgeCheck",     Icon: BadgeCheck,     label: "Badge Check",  category: "👑 Rank & Awards" },
  { key: "BadgeAlert",     Icon: BadgeAlert,     label: "Badge Alert",  category: "👑 Rank & Awards" },
  { key: "BadgeDollarSign",Icon: BadgeDollarSign,label: "Badge $",      category: "👑 Rank & Awards" },
  { key: "BadgeInfo",      Icon: BadgeInfo,      label: "Badge Info",   category: "👑 Rank & Awards" },
  { key: "BadgeMinus",     Icon: BadgeMinus,     label: "Badge Minus",  category: "👑 Rank & Awards" },
  { key: "BadgePlus",      Icon: BadgePlus,      label: "Badge Plus",   category: "👑 Rank & Awards" },
  { key: "BadgeX",         Icon: BadgeX,         label: "Badge X",      category: "👑 Rank & Awards" },
  { key: "Verified",       Icon: Verified,       label: "Verified",     category: "👑 Rank & Awards" },
  { key: "Dice1",          Icon: Dice1,          label: "Dice 1",       category: "👑 Rank & Awards" },
  { key: "Dice2",          Icon: Dice2,          label: "Dice 2",       category: "👑 Rank & Awards" },
  { key: "Dice3",          Icon: Dice3,          label: "Dice 3",       category: "👑 Rank & Awards" },
  { key: "Dice4",          Icon: Dice4,          label: "Dice 4",       category: "👑 Rank & Awards" },
  { key: "Dice5",          Icon: Dice5,          label: "Dice 5",       category: "👑 Rank & Awards" },
  { key: "Dice6",          Icon: Dice6,          label: "Dice 6",       category: "👑 Rank & Awards" },

  // ─── Animals & Nature ──────────────────────────────────────────────────────
  { key: "Snail",          Icon: Snail,          label: "Snail",        category: "🐾 Animals & Nature" },
  { key: "Turtle",         Icon: Turtle,         label: "Turtle",       category: "🐾 Animals & Nature" },
  { key: "Bug",            Icon: Bug,            label: "Bug",          category: "🐾 Animals & Nature" },
  { key: "Bird",           Icon: Bird,           label: "Bird",         category: "🐾 Animals & Nature" },
  { key: "Fish",           Icon: Fish,           label: "Fish",         category: "🐾 Animals & Nature" },
  { key: "Worm",           Icon: Worm,           label: "Worm",         category: "🐾 Animals & Nature" },
  { key: "Dog",            Icon: Dog,            label: "Dog",          category: "🐾 Animals & Nature" },
  { key: "Cat",            Icon: Cat,            label: "Cat",          category: "🐾 Animals & Nature" },
  { key: "Egg",            Icon: Egg,            label: "Egg",          category: "🐾 Animals & Nature" },
  { key: "Shell",          Icon: Shell,          label: "Shell",        category: "🐾 Animals & Nature" },
  { key: "Leaf",           Icon: Leaf,           label: "Leaf",         category: "🐾 Animals & Nature" },
  { key: "TreePine",       Icon: TreePine,       label: "Pine Tree",    category: "🐾 Animals & Nature" },
  { key: "Flower",         Icon: Flower,         label: "Flower",       category: "🐾 Animals & Nature" },
  { key: "Flower2",        Icon: Flower2,        label: "Flower 2",     category: "🐾 Animals & Nature" },
  { key: "Sprout",         Icon: Sprout,         label: "Sprout",       category: "🐾 Animals & Nature" },
  { key: "Sun",            Icon: Sun,            label: "Sun",          category: "🐾 Animals & Nature" },
  { key: "Moon",           Icon: Moon,           label: "Moon",         category: "🐾 Animals & Nature" },
  { key: "Sunrise",        Icon: Sunrise,        label: "Sunrise",      category: "🐾 Animals & Nature" },
  { key: "Sunset",         Icon: Sunset,         label: "Sunset",       category: "🐾 Animals & Nature" },
  { key: "Rainbow",        Icon: Rainbow,        label: "Rainbow",      category: "🐾 Animals & Nature" },
  { key: "Snowflake",      Icon: Snowflake,      label: "Snowflake",    category: "🐾 Animals & Nature" },
  { key: "CloudRain",      Icon: CloudRain,      label: "Cloud Rain",   category: "🐾 Animals & Nature" },
  { key: "CloudLightning", Icon: CloudLightning, label: "Lightning",    category: "🐾 Animals & Nature" },
  { key: "CloudSnow",      Icon: CloudSnow,      label: "Cloud Snow",   category: "🐾 Animals & Nature" },
  { key: "Cloud",          Icon: Cloud,          label: "Cloud",        category: "🐾 Animals & Nature" },
  { key: "Droplet",        Icon: Droplet,        label: "Droplet",      category: "🐾 Animals & Nature" },
  { key: "Droplets",       Icon: Droplets,       label: "Droplets",     category: "🐾 Animals & Nature" },
  { key: "Waves",          Icon: Waves,          label: "Waves",        category: "🐾 Animals & Nature" },
  { key: "Mountain",       Icon: Mountain,       label: "Mountain",     category: "🐾 Animals & Nature" },
  { key: "MountainSnow",   Icon: MountainSnow,   label: "Snowy Mountain",category: "🐾 Animals & Nature" },
  { key: "Flame_nature",   Icon: Flame,          label: "Fire",         category: "🐾 Animals & Nature" },

  // ─── People & Emotions ─────────────────────────────────────────────────────
  { key: "User",           Icon: User,           label: "User",         category: "👤 People & Emotions" },
  { key: "UserCheck",      Icon: UserCheck,      label: "User Check",   category: "👤 People & Emotions" },
  { key: "UserMinus",      Icon: UserMinus,      label: "User Minus",   category: "👤 People & Emotions" },
  { key: "UserPlus",       Icon: UserPlus,       label: "User Plus",    category: "👤 People & Emotions" },
  { key: "UserX",          Icon: UserX,          label: "User X",       category: "👤 People & Emotions" },
  { key: "Users",          Icon: Users,          label: "Users",        category: "👤 People & Emotions" },
  { key: "Heart",          Icon: Heart,          label: "Heart",        category: "👤 People & Emotions" },
  { key: "HeartCrack",     Icon: HeartCrack,     label: "Broken Heart", category: "👤 People & Emotions" },
  { key: "HeartHandshake", Icon: HeartHandshake, label: "Heart Shake",  category: "👤 People & Emotions" },
  { key: "HeartOff",       Icon: HeartOff,       label: "Heart Off",    category: "👤 People & Emotions" },
  { key: "HeartPulse",     Icon: HeartPulse,     label: "Heart Pulse",  category: "👤 People & Emotions" },
  { key: "Smile",          Icon: Smile,          label: "Smile",        category: "👤 People & Emotions" },
  { key: "Frown",          Icon: Frown,          label: "Frown",        category: "👤 People & Emotions" },
  { key: "Meh",            Icon: Meh,            label: "Meh",          category: "👤 People & Emotions" },
  { key: "Laugh",          Icon: Laugh,          label: "Laugh",        category: "👤 People & Emotions" },
  { key: "ThumbsUp",       Icon: ThumbsUp,       label: "Thumbs Up",    category: "👤 People & Emotions" },
  { key: "ThumbsDown",     Icon: ThumbsDown,     label: "Thumbs Down",  category: "👤 People & Emotions" },
  { key: "Baby",           Icon: Baby,           label: "Baby",         category: "👤 People & Emotions" },
  { key: "Ghost",          Icon: Ghost,          label: "Ghost",        category: "👤 People & Emotions" },
  { key: "Skull",          Icon: Skull,          label: "Skull",        category: "👤 People & Emotions" },
  { key: "PersonStanding", Icon: PersonStanding, label: "Person",       category: "👤 People & Emotions" },
  { key: "HandCoins",      Icon: HandCoins,      label: "Hand Coins",   category: "👤 People & Emotions" },
  { key: "HandHeart",      Icon: HeartHandshake, label: "Hand Heart",   category: "👤 People & Emotions" },

  // ─── Tech & Devices ────────────────────────────────────────────────────────
  { key: "Code",           Icon: Code,           label: "Code",         category: "⚙️ Tech & Devices" },
  { key: "Code2",          Icon: Code2,          label: "Code 2",       category: "⚙️ Tech & Devices" },
  { key: "Terminal",       Icon: Terminal,       label: "Terminal",     category: "⚙️ Tech & Devices" },
  { key: "Monitor",        Icon: Monitor,        label: "Monitor",      category: "⚙️ Tech & Devices" },
  { key: "Laptop",         Icon: Laptop,         label: "Laptop",       category: "⚙️ Tech & Devices" },
  { key: "Tablet",         Icon: Tablet,         label: "Tablet",       category: "⚙️ Tech & Devices" },
  { key: "Smartphone",     Icon: Smartphone,     label: "Smartphone",   category: "⚙️ Tech & Devices" },
  { key: "Tv",             Icon: Tv,             label: "TV",           category: "⚙️ Tech & Devices" },
  { key: "Watch",          Icon: Watch,          label: "Watch",        category: "⚙️ Tech & Devices" },
  { key: "Cpu",            Icon: Cpu,            label: "CPU",          category: "⚙️ Tech & Devices" },
  { key: "HardDrive",      Icon: HardDrive,      label: "Hard Drive",   category: "⚙️ Tech & Devices" },
  { key: "Server",         Icon: Server,         label: "Server",       category: "⚙️ Tech & Devices" },
  { key: "Database",       Icon: Database,       label: "Database",     category: "⚙️ Tech & Devices" },
  { key: "DatabaseBackup", Icon: DatabaseBackup, label: "DB Backup",    category: "⚙️ Tech & Devices" },
  { key: "DatabaseZap",    Icon: DatabaseZap,    label: "DB Zap",       category: "⚙️ Tech & Devices" },
  { key: "Globe",          Icon: Globe,          label: "Globe",        category: "⚙️ Tech & Devices" },
  { key: "Globe2",         Icon: Globe2,         label: "Globe 2",      category: "⚙️ Tech & Devices" },
  { key: "Wifi",           Icon: Wifi,           label: "Wifi",         category: "⚙️ Tech & Devices" },
  { key: "WifiOff",        Icon: WifiOff,        label: "Wifi Off",     category: "⚙️ Tech & Devices" },
  { key: "Bluetooth",      Icon: Bluetooth,      label: "Bluetooth",    category: "⚙️ Tech & Devices" },
  { key: "Radio",          Icon: Radio,          label: "Radio",        category: "⚙️ Tech & Devices" },
  { key: "Plug",           Icon: Plug,           label: "Plug",         category: "⚙️ Tech & Devices" },
  { key: "Unplug",         Icon: Unplug,         label: "Unplug",       category: "⚙️ Tech & Devices" },
  { key: "Camera",         Icon: Camera,         label: "Camera",       category: "⚙️ Tech & Devices" },
  { key: "Video",          Icon: Video,          label: "Video",        category: "⚙️ Tech & Devices" },
  { key: "Image",          Icon: Image,          label: "Image",        category: "⚙️ Tech & Devices" },
  { key: "Mic",            Icon: Mic,            label: "Mic",          category: "⚙️ Tech & Devices" },
  { key: "MicOff",         Icon: MicOff,         label: "Mic Off",      category: "⚙️ Tech & Devices" },
  { key: "Speaker",        Icon: Speaker,        label: "Speaker",      category: "⚙️ Tech & Devices" },
  { key: "Volume",         Icon: Volume,         label: "Volume",       category: "⚙️ Tech & Devices" },
  { key: "Volume1",        Icon: Volume1,        label: "Volume 1",     category: "⚙️ Tech & Devices" },
  { key: "Volume2",        Icon: Volume2,        label: "Volume 2",     category: "⚙️ Tech & Devices" },
  { key: "VolumeX",        Icon: VolumeX,        label: "Mute",         category: "⚙️ Tech & Devices" },
  { key: "Headphones",     Icon: Headphones,     label: "Headphones",   category: "⚙️ Tech & Devices" },
  { key: "Keyboard",       Icon: Keyboard,       label: "Keyboard",     category: "⚙️ Tech & Devices" },
  { key: "Mouse",          Icon: Mouse,          label: "Mouse",        category: "⚙️ Tech & Devices" },
  { key: "Power",          Icon: Power,          label: "Power",        category: "⚙️ Tech & Devices" },
  { key: "Binary",         Icon: Binary,         label: "Binary",       category: "⚙️ Tech & Devices" },
  { key: "Network",        Icon: Network,        label: "Network",      category: "⚙️ Tech & Devices" },
  { key: "Layers",         Icon: Layers,         label: "Layers",       category: "⚙️ Tech & Devices" },

  // ─── Security & Safety ─────────────────────────────────────────────────────
  { key: "Shield",         Icon: Shield,         label: "Shield",       category: "🔒 Security & Safety" },
  { key: "ShieldCheck",    Icon: ShieldCheck,    label: "Shield Check", category: "🔒 Security & Safety" },
  { key: "ShieldAlert",    Icon: ShieldAlert,    label: "Shield Alert", category: "🔒 Security & Safety" },
  { key: "ShieldOff",      Icon: ShieldOff,      label: "Shield Off",   category: "🔒 Security & Safety" },
  { key: "ShieldX",        Icon: ShieldX,        label: "Shield X",     category: "🔒 Security & Safety" },
  { key: "Lock",           Icon: Lock,           label: "Lock",         category: "🔒 Security & Safety" },
  { key: "LockOpen",       Icon: LockOpen,       label: "Unlocked",     category: "🔒 Security & Safety" },
  { key: "LockKeyhole",    Icon: LockKeyhole,    label: "Keyhole Lock", category: "🔒 Security & Safety" },
  { key: "Key",            Icon: Key,            label: "Key",          category: "🔒 Security & Safety" },
  { key: "KeyRound",       Icon: KeyRound,       label: "Key Round",    category: "🔒 Security & Safety" },
  { key: "Eye",            Icon: Eye,            label: "Eye",          category: "🔒 Security & Safety" },
  { key: "EyeOff",         Icon: EyeOff,         label: "Eye Off",      category: "🔒 Security & Safety" },
  { key: "Fingerprint",    Icon: Fingerprint,    label: "Fingerprint",  category: "🔒 Security & Safety" },
  { key: "AlertTriangle",  Icon: AlertTriangle,  label: "Alert",        category: "🔒 Security & Safety" },
  { key: "AlertCircle",    Icon: AlertCircle,    label: "Alert Circle", category: "🔒 Security & Safety" },
  { key: "AlertOctagon",   Icon: AlertOctagon,   label: "Alert Stop",   category: "🔒 Security & Safety" },
  { key: "Scan",           Icon: Scan,           label: "Scan",         category: "🔒 Security & Safety" },
  { key: "QrCode",         Icon: QrCode,         label: "QR Code",      category: "🔒 Security & Safety" },

  // ─── Finance & Trade ───────────────────────────────────────────────────────
  { key: "DollarSign",     Icon: DollarSign,     label: "Dollar",       category: "💰 Finance & Trade" },
  { key: "Euro",           Icon: Euro,           label: "Euro",         category: "💰 Finance & Trade" },
  { key: "Bitcoin",        Icon: Bitcoin,        label: "Bitcoin",      category: "💰 Finance & Trade" },
  { key: "CreditCard",     Icon: CreditCard,     label: "Credit Card",  category: "💰 Finance & Trade" },
  { key: "Wallet",         Icon: Wallet,         label: "Wallet",       category: "💰 Finance & Trade" },
  { key: "Coins",          Icon: Coins,          label: "Coins",        category: "💰 Finance & Trade" },
  { key: "Banknote",       Icon: Banknote,       label: "Banknote",     category: "💰 Finance & Trade" },
  { key: "Receipt",        Icon: Receipt,        label: "Receipt",      category: "💰 Finance & Trade" },
  { key: "ShoppingCart",   Icon: ShoppingCart,   label: "Cart",         category: "💰 Finance & Trade" },
  { key: "ShoppingBag",    Icon: ShoppingBag,    label: "Shopping Bag", category: "💰 Finance & Trade" },
  { key: "Store",          Icon: Store,          label: "Store",        category: "💰 Finance & Trade" },
  { key: "Package",        Icon: Package,        label: "Package",      category: "💰 Finance & Trade" },
  { key: "Tag",            Icon: Tag,            label: "Tag",          category: "💰 Finance & Trade" },
  { key: "Tags",           Icon: Tags,           label: "Tags",         category: "💰 Finance & Trade" },
  { key: "Percent",        Icon: Percent,        label: "Percent",      category: "💰 Finance & Trade" },
  { key: "Scale",          Icon: Scale,          label: "Scale",        category: "💰 Finance & Trade" },
  { key: "Calculator",     Icon: Calculator,     label: "Calculator",   category: "💰 Finance & Trade" },
  { key: "PieChart",       Icon: PieChart,       label: "Pie Chart",    category: "💰 Finance & Trade" },

  // ─── Communication ─────────────────────────────────────────────────────────
  { key: "MessageCircle",  Icon: MessageCircle,  label: "Message",      category: "💬 Communication" },
  { key: "MessageSquare",  Icon: MessageSquare,  label: "Message Sq",   category: "💬 Communication" },
  { key: "Mail",           Icon: Mail,           label: "Mail",         category: "💬 Communication" },
  { key: "MailOpen",       Icon: MailOpen,       label: "Mail Open",    category: "💬 Communication" },
  { key: "Phone",          Icon: Phone,          label: "Phone",        category: "💬 Communication" },
  { key: "PhoneCall",      Icon: PhoneCall,      label: "Phone Call",   category: "💬 Communication" },
  { key: "PhoneIncoming",  Icon: PhoneIncoming,  label: "Incoming",     category: "💬 Communication" },
  { key: "PhoneOutgoing",  Icon: PhoneOutgoing,  label: "Outgoing",     category: "💬 Communication" },
  { key: "PhoneMissed",    Icon: PhoneMissed,    label: "Missed Call",  category: "💬 Communication" },
  { key: "PhoneOff",       Icon: PhoneOff,       label: "Phone Off",    category: "💬 Communication" },
  { key: "Send",           Icon: Send,           label: "Send",         category: "💬 Communication" },
  { key: "Megaphone",      Icon: Megaphone,      label: "Megaphone",    category: "💬 Communication" },
  { key: "Bell",           Icon: Bell,           label: "Bell",         category: "💬 Communication" },
  { key: "BellDot",        Icon: BellDot,        label: "Bell Dot",     category: "💬 Communication" },
  { key: "BellOff",        Icon: BellOff,        label: "Bell Off",     category: "💬 Communication" },
  { key: "BellPlus",       Icon: BellPlus,       label: "Bell Plus",    category: "💬 Communication" },
  { key: "BellRing",       Icon: BellRing,       label: "Bell Ring",    category: "💬 Communication" },
  { key: "Share",          Icon: Share,          label: "Share",        category: "💬 Communication" },
  { key: "Share2",         Icon: Share2,         label: "Share 2",      category: "💬 Communication" },
  { key: "Link",           Icon: Link,           label: "Link",         category: "💬 Communication" },
  { key: "Link2",          Icon: Link2,          label: "Link 2",       category: "💬 Communication" },
  { key: "ExternalLink",   Icon: ExternalLink,   label: "External Link",category: "💬 Communication" },
  { key: "Rss",            Icon: Rss,            label: "RSS",          category: "💬 Communication" },
  { key: "Podcast",        Icon: Podcast,        label: "Podcast",      category: "💬 Communication" },
  { key: "Forward",        Icon: Forward,        label: "Forward",      category: "💬 Communication" },
  { key: "Reply",          Icon: Reply,          label: "Reply",        category: "💬 Communication" },

  // ─── Media & Entertainment ─────────────────────────────────────────────────
  { key: "Play",           Icon: Play,           label: "Play",         category: "🎬 Media & Entertainment" },
  { key: "Pause",          Icon: Pause,          label: "Pause",        category: "🎬 Media & Entertainment" },
  { key: "Music",          Icon: Music,          label: "Music",        category: "🎬 Media & Entertainment" },
  { key: "Music2",         Icon: Music2,         label: "Music Note",   category: "🎬 Media & Entertainment" },
  { key: "Film",           Icon: Film,           label: "Film",         category: "🎬 Media & Entertainment" },
  { key: "Tv2",            Icon: Tv2,            label: "TV 2",         category: "🎬 Media & Entertainment" },
  { key: "Clapperboard",   Icon: Clapperboard,   label: "Clapperboard", category: "🎬 Media & Entertainment" },
  { key: "Disc",           Icon: Disc,           label: "Disc",         category: "🎬 Media & Entertainment" },
  { key: "Disc2",          Icon: Disc2,          label: "Disc 2",       category: "🎬 Media & Entertainment" },
  { key: "Disc3",          Icon: Disc3,          label: "Disc 3",       category: "🎬 Media & Entertainment" },
  { key: "BookOpen",       Icon: BookOpen,       label: "Book Open",    category: "🎬 Media & Entertainment" },
  { key: "Book",           Icon: Book,           label: "Book",         category: "🎬 Media & Entertainment" },
  { key: "BookMarked",     Icon: BookMarked,     label: "Bookmarked",   category: "🎬 Media & Entertainment" },
  { key: "ScrollText",     Icon: ScrollText,     label: "Scroll Text",  category: "🎬 Media & Entertainment" },
  { key: "Gamepad",        Icon: Gamepad,        label: "Gamepad",      category: "🎬 Media & Entertainment" },
  { key: "Gamepad2",       Icon: Gamepad2,       label: "Gamepad 2",    category: "🎬 Media & Entertainment" },
  { key: "Joystick",       Icon: Joystick,       label: "Joystick",     category: "🎬 Media & Entertainment" },
  { key: "ListMusic",      Icon: ListMusic,      label: "Playlist",     category: "🎬 Media & Entertainment" },

  // ─── Sports & Action ───────────────────────────────────────────────────────
  { key: "Dumbbell",       Icon: Dumbbell,       label: "Dumbbell",     category: "🏋️ Sports & Action" },
  { key: "Target",         Icon: Target,         label: "Target",       category: "🏋️ Sports & Action" },
  { key: "Crosshair",      Icon: Crosshair,      label: "Crosshair",    category: "🏋️ Sports & Action" },
  { key: "Swords",         Icon: Swords,         label: "Swords",       category: "🏋️ Sports & Action" },
  { key: "Sword",          Icon: Sword,          label: "Sword",        category: "🏋️ Sports & Action" },
  { key: "Axe",            Icon: Axe,            label: "Axe",          category: "🏋️ Sports & Action" },
  { key: "Bomb",           Icon: Bomb,           label: "Bomb",         category: "🏋️ Sports & Action" },
  { key: "Flag",           Icon: Flag,           label: "Flag",         category: "🏋️ Sports & Action" },
  { key: "FlagOff",        Icon: FlagOff,        label: "Flag Off",     category: "🏋️ Sports & Action" },
  { key: "Move",           Icon: Move,           label: "Move",         category: "🏋️ Sports & Action" },
  { key: "MoveRight",      Icon: MoveRight,      label: "Move Right",   category: "🏋️ Sports & Action" },
  { key: "MoveUp",         Icon: MoveUp,         label: "Move Up",      category: "🏋️ Sports & Action" },
  { key: "Navigation",     Icon: Navigation,     label: "Navigation",   category: "🏋️ Sports & Action" },
  { key: "Navigation2",    Icon: Navigation2,    label: "Navigation 2", category: "🏋️ Sports & Action" },
  { key: "Compass",        Icon: Compass,        label: "Compass",      category: "🏋️ Sports & Action" },

  // ─── Symbols & Signs ───────────────────────────────────────────────────────
  { key: "Infinity",       Icon: Infinity,       label: "Infinity",     category: "🔣 Symbols & Signs" },
  { key: "Hash",           Icon: Hash,           label: "Hash",         category: "🔣 Symbols & Signs" },
  { key: "AtSign",         Icon: AtSign,         label: "At Sign",      category: "🔣 Symbols & Signs" },
  { key: "Asterisk",       Icon: Asterisk,       label: "Asterisk",     category: "🔣 Symbols & Signs" },
  { key: "Plus",           Icon: Plus,           label: "Plus",         category: "🔣 Symbols & Signs" },
  { key: "Minus",          Icon: Minus,          label: "Minus",        category: "🔣 Symbols & Signs" },
  { key: "Divide",         Icon: Divide,         label: "Divide",       category: "🔣 Symbols & Signs" },
  { key: "CheckCircle",    Icon: CheckCircle,    label: "Check Circle", category: "🔣 Symbols & Signs" },
  { key: "CheckCircle2",   Icon: CheckCircle2,   label: "Check Circle 2",category: "🔣 Symbols & Signs" },
  { key: "XCircle",        Icon: XCircle,        label: "X Circle",     category: "🔣 Symbols & Signs" },
  { key: "Circle",         Icon: Circle,         label: "Circle",       category: "🔣 Symbols & Signs" },
  { key: "CircleDot",      Icon: CircleDot,      label: "Circle Dot",   category: "🔣 Symbols & Signs" },
  { key: "CirclePlus",     Icon: CirclePlus,     label: "Circle Plus",  category: "🔣 Symbols & Signs" },
  { key: "CircleMinus",    Icon: CircleMinus,    label: "Circle Minus", category: "🔣 Symbols & Signs" },
  { key: "Triangle",       Icon: Triangle,       label: "Triangle",     category: "🔣 Symbols & Signs" },
  { key: "Square",         Icon: Square,         label: "Square",       category: "🔣 Symbols & Signs" },
  { key: "Pentagon",       Icon: Pentagon,       label: "Pentagon",     category: "🔣 Symbols & Signs" },
  { key: "Hexagon",        Icon: Hexagon,        label: "Hexagon",      category: "🔣 Symbols & Signs" },
  { key: "Octagon",        Icon: Octagon,        label: "Octagon",      category: "🔣 Symbols & Signs" },
  { key: "Info",           Icon: Info,           label: "Info",         category: "🔣 Symbols & Signs" },
  { key: "HelpCircle",     Icon: HelpCircle,     label: "Help",         category: "🔣 Symbols & Signs" },
  { key: "Ban",            Icon: Ban,            label: "Ban",          category: "🔣 Symbols & Signs" },
  { key: "Slash",          Icon: Slash,          label: "Slash",        category: "🔣 Symbols & Signs" },
  { key: "Copyright",      Icon: Copyright,      label: "Copyright",    category: "🔣 Symbols & Signs" },
  { key: "ChevronRight",   Icon: ChevronRight,   label: "Chevron Right",category: "🔣 Symbols & Signs" },
  { key: "ChevronLeft",    Icon: ChevronLeft,    label: "Chevron Left", category: "🔣 Symbols & Signs" },
  { key: "ChevronUp",      Icon: ChevronUp,      label: "Chevron Up",   category: "🔣 Symbols & Signs" },
  { key: "ChevronDown",    Icon: ChevronDown,    label: "Chevron Down", category: "🔣 Symbols & Signs" },

  // ─── World & Places ────────────────────────────────────────────────────────
  { key: "Map",            Icon: MapIcon,        label: "Map",          category: "🌍 World & Places" },
  { key: "MapPin",         Icon: MapPin,         label: "Map Pin",      category: "🌍 World & Places" },
  { key: "Landmark",       Icon: Landmark,       label: "Landmark",     category: "🌍 World & Places" },
  { key: "Home",           Icon: Home,           label: "Home",         category: "🌍 World & Places" },
  { key: "Building",       Icon: Building,       label: "Building",     category: "🌍 World & Places" },
  { key: "Building2",      Icon: Building2,      label: "Building 2",   category: "🌍 World & Places" },
  { key: "Hotel",          Icon: Hotel,          label: "Hotel",        category: "🌍 World & Places" },
  { key: "School",         Icon: School,         label: "School",       category: "🌍 World & Places" },
  { key: "Hospital",       Icon: Hospital,       label: "Hospital",     category: "🌍 World & Places" },
  { key: "Plane",          Icon: Plane,          label: "Plane",        category: "🌍 World & Places" },
  { key: "Car",            Icon: Car,            label: "Car",          category: "🌍 World & Places" },
  { key: "Truck",          Icon: Truck,          label: "Truck",        category: "🌍 World & Places" },
  { key: "Bike",           Icon: Bike,           label: "Bike",         category: "🌍 World & Places" },
  { key: "Ship",           Icon: Ship,           label: "Ship",         category: "🌍 World & Places" },
  { key: "Train",          Icon: Train,          label: "Train",        category: "🌍 World & Places" },
  { key: "Bus",            Icon: Bus,            label: "Bus",          category: "🌍 World & Places" },
  { key: "Sailboat",       Icon: Sailboat,       label: "Sailboat",     category: "🌍 World & Places" },
  { key: "Tent",           Icon: Tent,           label: "Tent",         category: "🌍 World & Places" },
  { key: "Castle",         Icon: Castle,         label: "Castle",       category: "🌍 World & Places" },

  // ─── Food & Life ───────────────────────────────────────────────────────────
  { key: "Coffee",         Icon: Coffee,         label: "Coffee",       category: "🍕 Food & Life" },
  { key: "Beer",           Icon: Beer,           label: "Beer",         category: "🍕 Food & Life" },
  { key: "Wine",           Icon: Wine,           label: "Wine",         category: "🍕 Food & Life" },
  { key: "Pizza",          Icon: Pizza,          label: "Pizza",        category: "🍕 Food & Life" },
  { key: "Apple",          Icon: Apple,          label: "Apple",        category: "🍕 Food & Life" },
  { key: "Cherry",         Icon: Cherry,         label: "Cherry",       category: "🍕 Food & Life" },
  { key: "Banana",         Icon: Banana,         label: "Banana",       category: "🍕 Food & Life" },
  { key: "IceCream2",      Icon: IceCream2,      label: "Ice Cream",    category: "🍕 Food & Life" },
  { key: "Cookie",         Icon: Cookie,         label: "Cookie",       category: "🍕 Food & Life" },
  { key: "Cake",           Icon: Cake,           label: "Cake",         category: "🍕 Food & Life" },
  { key: "Croissant",      Icon: Croissant,      label: "Croissant",    category: "🍕 Food & Life" },
  { key: "Sandwich",       Icon: Sandwich,       label: "Sandwich",     category: "🍕 Food & Life" },
  { key: "Soup",           Icon: Soup,           label: "Soup",         category: "🍕 Food & Life" },
  { key: "Salad",          Icon: Salad,          label: "Salad",        category: "🍕 Food & Life" },
  { key: "IceCream",       Icon: IceCream,       label: "Ice Cream 2",  category: "🍕 Food & Life" },
  { key: "Donut",          Icon: Donut,          label: "Donut",        category: "🍕 Food & Life" },
  { key: "ChefHat",        Icon: ChefHat,        label: "Chef Hat",     category: "🍕 Food & Life" },
  { key: "UtensilsCrossed",Icon: UtensilsCrossed,label: "Utensils X",   category: "🍕 Food & Life" },
  { key: "Utensils",       Icon: Utensils,       label: "Utensils",     category: "🍕 Food & Life" },
  { key: "CookingPot",     Icon: CookingPot,     label: "Cooking Pot",  category: "🍕 Food & Life" },
  { key: "Microwave",      Icon: Microwave,      label: "Microwave",    category: "🍕 Food & Life" },
  { key: "Refrigerator",   Icon: Refrigerator,   label: "Fridge",       category: "🍕 Food & Life" },
  { key: "Gift",           Icon: Gift,           label: "Gift",         category: "🍕 Food & Life" },
  { key: "PartyPopper",    Icon: PartyPopper,    label: "Party",        category: "🍕 Food & Life" },
  { key: "Anchor",         Icon: Anchor,         label: "Anchor",       category: "🍕 Food & Life" },
  { key: "Hourglass",      Icon: Hourglass,      label: "Hourglass",    category: "🍕 Food & Life" },
  { key: "Umbrella",       Icon: Umbrella,       label: "Umbrella",     category: "🍕 Food & Life" },
  { key: "Magnet",         Icon: Magnet,         label: "Magnet",       category: "🍕 Food & Life" },
  { key: "Lightbulb",      Icon: Lightbulb,      label: "Lightbulb",    category: "🍕 Food & Life" },

  // ─── Design & Tools ────────────────────────────────────────────────────────
  { key: "Palette",        Icon: Palette,        label: "Palette",      category: "🎨 Design & Tools" },
  { key: "Paintbrush",     Icon: Paintbrush,     label: "Paintbrush",   category: "🎨 Design & Tools" },
  { key: "PaintBucket",    Icon: PaintBucket,    label: "Paint Bucket", category: "🎨 Design & Tools" },
  { key: "Pipette",        Icon: Pipette,        label: "Pipette",      category: "🎨 Design & Tools" },
  { key: "Eraser",         Icon: Eraser,         label: "Eraser",       category: "🎨 Design & Tools" },
  { key: "Pencil",         Icon: Pencil,         label: "Pencil",       category: "🎨 Design & Tools" },
  { key: "Pen",            Icon: Pen,            label: "Pen",          category: "🎨 Design & Tools" },
  { key: "PenLine",        Icon: PenLine,        label: "Pen Line",     category: "🎨 Design & Tools" },
  { key: "Highlighter",    Icon: Highlighter,    label: "Highlighter",  category: "🎨 Design & Tools" },
  { key: "Scissors",       Icon: Scissors,       label: "Scissors",     category: "🎨 Design & Tools" },
  { key: "Crop",           Icon: Crop,           label: "Crop",         category: "🎨 Design & Tools" },
  { key: "Wand",           Icon: Wand,           label: "Wand",         category: "🎨 Design & Tools" },
  { key: "Wand2",          Icon: Wand2,          label: "Wand 2",       category: "🎨 Design & Tools" },
  { key: "Blend",          Icon: Blend,          label: "Blend",        category: "🎨 Design & Tools" },
  { key: "Blocks",         Icon: Blocks,         label: "Blocks",       category: "🎨 Design & Tools" },
  { key: "Wrench",         Icon: Wrench,         label: "Wrench",       category: "🎨 Design & Tools" },
  { key: "Hammer",         Icon: Hammer,         label: "Hammer",       category: "🎨 Design & Tools" },
  { key: "Cog",            Icon: Cog,            label: "Cog",          category: "🎨 Design & Tools" },
  { key: "Settings",       Icon: Settings,       label: "Settings",     category: "🎨 Design & Tools" },
  { key: "Settings2",      Icon: Settings2,      label: "Settings 2",   category: "🎨 Design & Tools" },
  { key: "Sliders",        Icon: Sliders,        label: "Sliders",      category: "🎨 Design & Tools" },
  { key: "SlidersHorizontal",Icon: SlidersHorizontal,label: "Sliders H",category: "🎨 Design & Tools" },
  { key: "FlaskConical",   Icon: FlaskConical,   label: "Flask",        category: "🎨 Design & Tools" },
  { key: "TestTube",       Icon: TestTube,       label: "Test Tube",    category: "🎨 Design & Tools" },
  { key: "TestTube2",      Icon: TestTube2,      label: "Test Tube 2",  category: "🎨 Design & Tools" },
  { key: "Atom",           Icon: Atom,           label: "Atom",         category: "🎨 Design & Tools" },
  { key: "Microscope",     Icon: Microscope,     label: "Microscope",   category: "🎨 Design & Tools" },
  { key: "Telescope",      Icon: Telescope,      label: "Telescope",    category: "🎨 Design & Tools" },
  { key: "Binoculars",     Icon: Binoculars,     label: "Binoculars",   category: "🎨 Design & Tools" },
  { key: "Bookmark",       Icon: Bookmark,       label: "Bookmark",     category: "🎨 Design & Tools" },
  { key: "BookmarkPlus",   Icon: BookmarkPlus,   label: "Bookmark +",   category: "🎨 Design & Tools" },
  { key: "Paperclip",      Icon: Paperclip,      label: "Paperclip",    category: "🎨 Design & Tools" },
  { key: "Pin",            Icon: Pin,            label: "Pin",          category: "🎨 Design & Tools" },
];

const _keyMap = new Map<string, LucideIcon>(
  ICON_REGISTRY.map(e => [e.key, e.Icon])
);

export function getIconByKey(key: string): LucideIcon | null {
  return _keyMap.get(key) ?? null;
}
