import type { LucideIcon } from "lucide-react";
import {
  // Speed & Power
  Zap, ZapOff, Rocket, Flame, Gauge, Activity, TrendingUp, TrendingDown,
  Wind, Timer, TimerOff, FastForward, Rewind, ChevronsRight, ChevronsLeft,
  ChevronsUp, ChevronsDown, ArrowBigUp, ArrowBigDown, ArrowBigRight, ArrowBigLeft,
  ChartBar, ChartLine, ChartArea, ChartBarBig, ChartBarDecreasing, ChartBarIncreasing,
  ChartBarStacked, ChartCandlestick, ChartColumn, ChartColumnBig, ChartColumnDecreasing,
  ChartColumnIncreasing, ChartColumnStacked, ChartGantt, ChartNetwork, ChartNoAxesColumn,
  ChartNoAxesCombined, ChartPie, ChartScatter, ChartSpline,
  RefreshCw, RefreshCcw, RotateCw, RotateCcw, Repeat, Repeat2,
  Battery, BatteryCharging, BatteryFull, BatteryLow,
  SkipForward, SkipBack, ChevronRight, ChevronLeft, ChevronUp, ChevronDown,
  ArrowUp, ArrowDown, ArrowLeft, ArrowRight, ArrowUpDown, ArrowLeftRight,
  ArrowDownUp, ArrowUpLeft, ArrowUpRight, ArrowDownLeft, ArrowDownRight,
  Maximize, Maximize2, Minimize, Minimize2,
  // Rank & Awards
  Crown, Trophy, Medal, Award, Star, StarHalf, StarOff,
  Diamond, Gem, Sparkles, Ribbon, BadgeCheck,
  BadgeAlert, BadgeDollarSign, BadgeInfo, BadgeMinus, BadgePlus, BadgeX,
  // Animals & Nature
  Snail, Turtle, Bug, Bird, Fish, Worm, Dog, Cat, Egg,
  Rabbit, Squirrel, Shrimp, PawPrint, Feather, Rat,
  Shell, Leaf, TreePine, TreeDeciduous, Trees, Palmtree, Flower, Flower2, Sprout,
  Rose, Clover, Wheat, WheatOff,
  Sun, Moon, Sunrise, Sunset, Rainbow, Snowflake,
  CloudRain, CloudLightning, CloudSnow, Cloud, CloudAlert, CloudCheck, CloudCog,
  CloudDrizzle, CloudFog, CloudHail, CloudMoon, CloudMoonRain, CloudOff,
  CloudRainWind, CloudSun, CloudSunRain, CloudDownload, CloudUpload,
  Droplet, Droplets, Waves, Mountain, MountainSnow,
  SunDim, SunMedium, SunMoon, SunSnow, MoonStar, Tornado, Haze, WindArrowDown,
  // People & Emotions
  User, UserCheck, UserMinus, UserPlus, UserX, Users,
  Heart, HeartCrack, HeartHandshake, HeartOff, HeartPulse,
  Smile, Frown, Meh, Laugh, ThumbsUp, ThumbsDown,
  Baby, Ghost, Skull, PersonStanding,
  Brain, BrainCircuit, BrainCog, Bone, Dna, DnaOff, Bandage,
  Hand, HandFist, HandGrab, HandHeart, HandHelping, HandMetal, HandPlatter, Handshake,
  Ear, EarOff, EyeClosed, Armchair, Ambulance,
  Stethoscope, Pill, PillBottle, Syringe, Thermometer, ThermometerSnowflake, ThermometerSun,
  HandCoins,
  // Tech & Devices
  Code, Code2, Terminal, Monitor, Laptop, Tablet, Smartphone, Tv, Watch,
  Cpu, HardDrive, HardDriveDownload, HardDriveUpload, Server, Database, DatabaseBackup, DatabaseZap,
  Globe, Wifi, WifiOff, Bluetooth, Radio, Plug, Unplug,
  Camera, Video, Image, Mic, MicOff, Speaker, Volume, Volume1, Volume2, VolumeX,
  Headphones, Keyboard, Mouse, Power, Binary, Network, Layers,
  CircuitBoard, Cable, Component, Nfc, Printer, PrinterCheck,
  Radar, Satellite, SatelliteDish, Signal, SignalHigh,
  ScanBarcode, ScanEye, ScanFace, ScanHeart, ScanLine, ScanSearch, ScanText,
  ServerCog, ServerCrash, ServerOff,
  MonitorCheck, MonitorCog, MonitorDot, MonitorOff, MonitorPause, MonitorPlay,
  MonitorSmartphone, MonitorStop, MonitorUp, MonitorX,
  BotMessageSquare, BotOff,
  // Security & Safety
  Shield, ShieldCheck, ShieldAlert, ShieldOff, ShieldX,
  Lock, LockOpen, LockKeyhole, Key, KeyRound, Eye, EyeOff, Fingerprint,
  TriangleAlert, CircleAlert, OctagonAlert, Scan, QrCode,
  // Finance & Business
  DollarSign, Euro, Bitcoin, CreditCard, Wallet, Coins, Banknote, Receipt,
  ShoppingCart, ShoppingBag, Store, Package, Tag, Tags, Percent,
  Scale, Calculator, PieChart,
  // Communication
  MessageCircle, MessageSquare, Mail, MailOpen, Phone, PhoneCall,
  PhoneIncoming, PhoneOutgoing, PhoneMissed, PhoneOff, Send,
  Megaphone, Bell, BellDot, BellOff, BellPlus, BellRing,
  Share, Share2, Link, Link2, ExternalLink, Rss, Podcast, Forward, Reply,
  // Media & Entertainment
  Play, Pause, Music, Music2, Film, Clapperboard,
  Disc, BookOpen, Book, BookMarked, ScrollText,
  Gamepad2, Joystick, Dice1, Dice2, Dice3, Dice4, Dice5, Dice6,
  // Sports & Action
  Dumbbell, Target, Crosshair, Swords, Sword, Axe, Bomb, Flag, FlagOff,
  Move, MoveRight, MoveLeft, MoveUp, MoveDown, Navigation, Navigation2, Compass,
  Weight, Kayak, Volleyball,
  // Symbols & Signs
  Infinity, Hash, AtSign, Asterisk, Plus, Minus, Divide,
  CircleCheck, CircleCheckBig, CircleX, Circle, CircleDot, CirclePlus, CircleMinus,
  Triangle, Square,
  Info, Ban, Slash, Copyright,
  // World & Places
  Map as MapIcon, MapPin, Landmark, Home, Building, Building2,
  Hotel, School, Hospital, Plane, Car, Truck, Bike, Ship, TrainFront, Bus,
  Sailboat, Tent, Castle,
  // Food & Life
  Coffee, Beer, Wine, Pizza, Apple, Cherry, Banana, IceCreamCone, Cookie,
  Cake, Croissant, Sandwich, Soup, Salad, Grape, Carrot, Bean, BeanOff, Nut, NutOff,
  Donut, EggFried, Lollipop, Popsicle,
  ChefHat, UtensilsCrossed, Utensils, CookingPot, Microwave, Refrigerator,
  // Shapes & Design
  Palette, Paintbrush, Eraser, Pencil, Pen, PenLine,
  Highlighter, Scissors, Crop, Wand, Blend, Blocks,
  // Tools & Build
  Wrench, Hammer, Cog, Settings, Settings2, SlidersHorizontal, SlidersVertical,
  FlaskConical, TestTube, Atom, Microscope, Telescope, Binoculars,
  // Misc
  Gift, PartyPopper, Sparkle, Lightbulb, LightbulbOff, Magnet,
  Anchor, Hourglass, Umbrella,
  Bookmark, BookmarkPlus, BookmarkCheck, BookmarkX,
  Paperclip, Pin, PinOff,
} from "lucide-react";

export interface IconEntry {
  key: string;
  Icon: LucideIcon;
  label: string;
  category: string;
}

export const ICON_CATEGORIES = [
  "All",
  "⚡ Speed & Power",
  "👑 Rank & Awards",
  "🐾 Animals & Nature",
  "👤 People & Emotions",
  "⚙️ Tech & Devices",
  "🔒 Security & Safety",
  "💰 Finance & Trade",
  "💬 Communication",
  "🎬 Media & Entertainment",
  "🏋️ Sports & Action",
  "🔣 Symbols & Signs",
  "🌍 World & Places",
  "🍕 Food & Life",
  "🎨 Design & Tools",
];

export const ICON_REGISTRY: IconEntry[] = [
  // ─── Speed & Power ─────────────────────────────────────────────────────────
  { key: "Zap",                    Icon: Zap,                    label: "Zap",               category: "⚡ Speed & Power" },
  { key: "ZapOff",                 Icon: ZapOff,                 label: "Zap Off",           category: "⚡ Speed & Power" },
  { key: "Rocket",                 Icon: Rocket,                 label: "Rocket",            category: "⚡ Speed & Power" },
  { key: "Flame",                  Icon: Flame,                  label: "Flame",             category: "⚡ Speed & Power" },
  { key: "Gauge",                  Icon: Gauge,                  label: "Gauge",             category: "⚡ Speed & Power" },
  { key: "Activity",               Icon: Activity,               label: "Activity",          category: "⚡ Speed & Power" },
  { key: "TrendingUp",             Icon: TrendingUp,             label: "Trending Up",       category: "⚡ Speed & Power" },
  { key: "TrendingDown",           Icon: TrendingDown,           label: "Trending Down",     category: "⚡ Speed & Power" },
  { key: "Wind",                   Icon: Wind,                   label: "Wind",              category: "⚡ Speed & Power" },
  { key: "Timer",                  Icon: Timer,                  label: "Timer",             category: "⚡ Speed & Power" },
  { key: "TimerOff",               Icon: TimerOff,               label: "Timer Off",         category: "⚡ Speed & Power" },
  { key: "FastForward",            Icon: FastForward,            label: "Fast Forward",      category: "⚡ Speed & Power" },
  { key: "Rewind",                 Icon: Rewind,                 label: "Rewind",            category: "⚡ Speed & Power" },
  { key: "ChevronsRight",          Icon: ChevronsRight,          label: "Chevrons Right",    category: "⚡ Speed & Power" },
  { key: "ChevronsLeft",           Icon: ChevronsLeft,           label: "Chevrons Left",     category: "⚡ Speed & Power" },
  { key: "ChevronsUp",             Icon: ChevronsUp,             label: "Chevrons Up",       category: "⚡ Speed & Power" },
  { key: "ChevronsDown",           Icon: ChevronsDown,           label: "Chevrons Down",     category: "⚡ Speed & Power" },
  { key: "ArrowBigUp",             Icon: ArrowBigUp,             label: "Arrow Big Up",      category: "⚡ Speed & Power" },
  { key: "ArrowBigDown",           Icon: ArrowBigDown,           label: "Arrow Big Down",    category: "⚡ Speed & Power" },
  { key: "ArrowBigRight",          Icon: ArrowBigRight,          label: "Arrow Big Right",   category: "⚡ Speed & Power" },
  { key: "ArrowBigLeft",           Icon: ArrowBigLeft,           label: "Arrow Big Left",    category: "⚡ Speed & Power" },
  { key: "ArrowUp",                Icon: ArrowUp,                label: "Arrow Up",          category: "⚡ Speed & Power" },
  { key: "ArrowDown",              Icon: ArrowDown,              label: "Arrow Down",        category: "⚡ Speed & Power" },
  { key: "ArrowLeft",              Icon: ArrowLeft,              label: "Arrow Left",        category: "⚡ Speed & Power" },
  { key: "ArrowRight",             Icon: ArrowRight,             label: "Arrow Right",       category: "⚡ Speed & Power" },
  { key: "ArrowUpDown",            Icon: ArrowUpDown,            label: "Arrow Up-Down",     category: "⚡ Speed & Power" },
  { key: "ArrowLeftRight",         Icon: ArrowLeftRight,         label: "Arrow Left-Right",  category: "⚡ Speed & Power" },
  { key: "ArrowUpLeft",            Icon: ArrowUpLeft,            label: "Arrow Up-Left",     category: "⚡ Speed & Power" },
  { key: "ArrowUpRight",           Icon: ArrowUpRight,           label: "Arrow Up-Right",    category: "⚡ Speed & Power" },
  { key: "ArrowDownLeft",          Icon: ArrowDownLeft,          label: "Arrow Down-Left",   category: "⚡ Speed & Power" },
  { key: "ArrowDownRight",         Icon: ArrowDownRight,         label: "Arrow Down-Right",  category: "⚡ Speed & Power" },
  { key: "ChartBar",               Icon: ChartBar,               label: "Bar Chart",         category: "⚡ Speed & Power" },
  { key: "ChartLine",              Icon: ChartLine,              label: "Line Chart",        category: "⚡ Speed & Power" },
  { key: "ChartArea",              Icon: ChartArea,              label: "Area Chart",        category: "⚡ Speed & Power" },
  { key: "ChartBarBig",            Icon: ChartBarBig,            label: "Bar Chart Big",     category: "⚡ Speed & Power" },
  { key: "ChartBarDecreasing",     Icon: ChartBarDecreasing,     label: "Bar Decreasing",    category: "⚡ Speed & Power" },
  { key: "ChartBarIncreasing",     Icon: ChartBarIncreasing,     label: "Bar Increasing",    category: "⚡ Speed & Power" },
  { key: "ChartBarStacked",        Icon: ChartBarStacked,        label: "Bar Stacked",       category: "⚡ Speed & Power" },
  { key: "ChartCandlestick",       Icon: ChartCandlestick,       label: "Candlestick",       category: "⚡ Speed & Power" },
  { key: "ChartColumn",            Icon: ChartColumn,            label: "Column Chart",      category: "⚡ Speed & Power" },
  { key: "ChartColumnBig",         Icon: ChartColumnBig,         label: "Column Big",        category: "⚡ Speed & Power" },
  { key: "ChartColumnDecreasing",  Icon: ChartColumnDecreasing,  label: "Col Decreasing",    category: "⚡ Speed & Power" },
  { key: "ChartColumnIncreasing",  Icon: ChartColumnIncreasing,  label: "Col Increasing",    category: "⚡ Speed & Power" },
  { key: "ChartColumnStacked",     Icon: ChartColumnStacked,     label: "Col Stacked",       category: "⚡ Speed & Power" },
  { key: "ChartGantt",             Icon: ChartGantt,             label: "Gantt Chart",       category: "⚡ Speed & Power" },
  { key: "ChartNetwork",           Icon: ChartNetwork,           label: "Network Chart",     category: "⚡ Speed & Power" },
  { key: "ChartNoAxesColumn",      Icon: ChartNoAxesColumn,      label: "No-Axes Col",       category: "⚡ Speed & Power" },
  { key: "ChartNoAxesCombined",    Icon: ChartNoAxesCombined,    label: "No-Axes Combined",  category: "⚡ Speed & Power" },
  { key: "ChartPie",               Icon: ChartPie,               label: "Pie Chart",         category: "⚡ Speed & Power" },
  { key: "ChartScatter",           Icon: ChartScatter,           label: "Scatter Plot",      category: "⚡ Speed & Power" },
  { key: "ChartSpline",            Icon: ChartSpline,            label: "Spline Chart",      category: "⚡ Speed & Power" },
  { key: "RefreshCw",              Icon: RefreshCw,              label: "Refresh CW",        category: "⚡ Speed & Power" },
  { key: "RefreshCcw",             Icon: RefreshCcw,             label: "Refresh CCW",       category: "⚡ Speed & Power" },
  { key: "RotateCw",               Icon: RotateCw,               label: "Rotate CW",         category: "⚡ Speed & Power" },
  { key: "RotateCcw",              Icon: RotateCcw,              label: "Rotate CCW",        category: "⚡ Speed & Power" },
  { key: "Repeat",                 Icon: Repeat,                 label: "Repeat",            category: "⚡ Speed & Power" },
  { key: "Repeat2",                Icon: Repeat2,                label: "Repeat 2",          category: "⚡ Speed & Power" },
  { key: "Battery",                Icon: Battery,                label: "Battery",           category: "⚡ Speed & Power" },
  { key: "BatteryCharging",        Icon: BatteryCharging,        label: "Charging",          category: "⚡ Speed & Power" },
  { key: "BatteryFull",            Icon: BatteryFull,            label: "Battery Full",      category: "⚡ Speed & Power" },
  { key: "BatteryLow",             Icon: BatteryLow,             label: "Battery Low",       category: "⚡ Speed & Power" },
  { key: "SkipForward",            Icon: SkipForward,            label: "Skip Forward",      category: "⚡ Speed & Power" },
  { key: "SkipBack",               Icon: SkipBack,               label: "Skip Back",         category: "⚡ Speed & Power" },
  { key: "Maximize",               Icon: Maximize,               label: "Maximize",          category: "⚡ Speed & Power" },
  { key: "Maximize2",              Icon: Maximize2,              label: "Maximize 2",        category: "⚡ Speed & Power" },
  { key: "Minimize",               Icon: Minimize,               label: "Minimize",          category: "⚡ Speed & Power" },
  { key: "Minimize2",              Icon: Minimize2,              label: "Minimize 2",        category: "⚡ Speed & Power" },

  // ─── Rank & Awards ─────────────────────────────────────────────────────────
  { key: "Crown",                  Icon: Crown,                  label: "Crown",             category: "👑 Rank & Awards" },
  { key: "Trophy",                 Icon: Trophy,                 label: "Trophy",            category: "👑 Rank & Awards" },
  { key: "Medal",                  Icon: Medal,                  label: "Medal",             category: "👑 Rank & Awards" },
  { key: "Award",                  Icon: Award,                  label: "Award",             category: "👑 Rank & Awards" },
  { key: "Star",                   Icon: Star,                   label: "Star",              category: "👑 Rank & Awards" },
  { key: "StarHalf",               Icon: StarHalf,               label: "Star Half",         category: "👑 Rank & Awards" },
  { key: "StarOff",                Icon: StarOff,                label: "Star Off",          category: "👑 Rank & Awards" },
  { key: "Diamond",                Icon: Diamond,                label: "Diamond",           category: "👑 Rank & Awards" },
  { key: "Gem",                    Icon: Gem,                    label: "Gem",               category: "👑 Rank & Awards" },
  { key: "Sparkles",               Icon: Sparkles,               label: "Sparkles",          category: "👑 Rank & Awards" },
  { key: "Sparkle",                Icon: Sparkle,                label: "Sparkle",           category: "👑 Rank & Awards" },
  { key: "Ribbon",                 Icon: Ribbon,                 label: "Ribbon",            category: "👑 Rank & Awards" },
  { key: "BadgeCheck",             Icon: BadgeCheck,             label: "Badge Check",       category: "👑 Rank & Awards" },
  { key: "BadgeAlert",             Icon: BadgeAlert,             label: "Badge Alert",       category: "👑 Rank & Awards" },
  { key: "BadgeDollarSign",        Icon: BadgeDollarSign,        label: "Badge $",           category: "👑 Rank & Awards" },
  { key: "BadgeInfo",              Icon: BadgeInfo,              label: "Badge Info",        category: "👑 Rank & Awards" },
  { key: "BadgeMinus",             Icon: BadgeMinus,             label: "Badge Minus",       category: "👑 Rank & Awards" },
  { key: "BadgePlus",              Icon: BadgePlus,              label: "Badge Plus",        category: "👑 Rank & Awards" },
  { key: "BadgeX",                 Icon: BadgeX,                 label: "Badge X",           category: "👑 Rank & Awards" },
  { key: "Dice1",                  Icon: Dice1,                  label: "Dice 1",            category: "👑 Rank & Awards" },
  { key: "Dice2",                  Icon: Dice2,                  label: "Dice 2",            category: "👑 Rank & Awards" },
  { key: "Dice3",                  Icon: Dice3,                  label: "Dice 3",            category: "👑 Rank & Awards" },
  { key: "Dice4",                  Icon: Dice4,                  label: "Dice 4",            category: "👑 Rank & Awards" },
  { key: "Dice5",                  Icon: Dice5,                  label: "Dice 5",            category: "👑 Rank & Awards" },
  { key: "Dice6",                  Icon: Dice6,                  label: "Dice 6",            category: "👑 Rank & Awards" },

  // ─── Animals & Nature ──────────────────────────────────────────────────────
  { key: "Rabbit",                 Icon: Rabbit,                 label: "Rabbit",            category: "🐾 Animals & Nature" },
  { key: "Rat",                    Icon: Rat,                    label: "Rat",               category: "🐾 Animals & Nature" },
  { key: "Dog",                    Icon: Dog,                    label: "Dog",               category: "🐾 Animals & Nature" },
  { key: "Cat",                    Icon: Cat,                    label: "Cat",               category: "🐾 Animals & Nature" },
  { key: "Bird",                   Icon: Bird,                   label: "Bird",              category: "🐾 Animals & Nature" },
  { key: "Fish",                   Icon: Fish,                   label: "Fish",              category: "🐾 Animals & Nature" },
  { key: "Squirrel",               Icon: Squirrel,               label: "Squirrel",          category: "🐾 Animals & Nature" },
  { key: "Turtle",                 Icon: Turtle,                 label: "Turtle",            category: "🐾 Animals & Nature" },
  { key: "Snail",                  Icon: Snail,                  label: "Snail",             category: "🐾 Animals & Nature" },
  { key: "Bug",                    Icon: Bug,                    label: "Bug",               category: "🐾 Animals & Nature" },
  { key: "Worm",                   Icon: Worm,                   label: "Worm",              category: "🐾 Animals & Nature" },
  { key: "Shrimp",                 Icon: Shrimp,                 label: "Shrimp",            category: "🐾 Animals & Nature" },
  { key: "Egg",                    Icon: Egg,                    label: "Egg",               category: "🐾 Animals & Nature" },
  { key: "PawPrint",               Icon: PawPrint,               label: "Paw Print",         category: "🐾 Animals & Nature" },
  { key: "Feather",                Icon: Feather,                label: "Feather",           category: "🐾 Animals & Nature" },
  { key: "Shell",                  Icon: Shell,                  label: "Shell",             category: "🐾 Animals & Nature" },
  { key: "Leaf",                   Icon: Leaf,                   label: "Leaf",              category: "🐾 Animals & Nature" },
  { key: "TreePine",               Icon: TreePine,               label: "Pine Tree",         category: "🐾 Animals & Nature" },
  { key: "TreeDeciduous",          Icon: TreeDeciduous,          label: "Tree",              category: "🐾 Animals & Nature" },
  { key: "Trees",                  Icon: Trees,                  label: "Forest",            category: "🐾 Animals & Nature" },
  { key: "Palmtree",               Icon: Palmtree,               label: "Palm Tree",         category: "🐾 Animals & Nature" },
  { key: "Flower",                 Icon: Flower,                 label: "Flower",            category: "🐾 Animals & Nature" },
  { key: "Flower2",                Icon: Flower2,                label: "Flower 2",          category: "🐾 Animals & Nature" },
  { key: "Rose",                   Icon: Rose,                   label: "Rose",              category: "🐾 Animals & Nature" },
  { key: "Clover",                 Icon: Clover,                 label: "Clover",            category: "🐾 Animals & Nature" },
  { key: "Sprout",                 Icon: Sprout,                 label: "Sprout",            category: "🐾 Animals & Nature" },
  { key: "Wheat",                  Icon: Wheat,                  label: "Wheat",             category: "🐾 Animals & Nature" },
  { key: "WheatOff",               Icon: WheatOff,               label: "Wheat Off",         category: "🐾 Animals & Nature" },
  { key: "Sun",                    Icon: Sun,                    label: "Sun",               category: "🐾 Animals & Nature" },
  { key: "SunDim",                 Icon: SunDim,                 label: "Sun Dim",           category: "🐾 Animals & Nature" },
  { key: "SunMedium",              Icon: SunMedium,              label: "Sun Medium",        category: "🐾 Animals & Nature" },
  { key: "SunMoon",                Icon: SunMoon,                label: "Sun & Moon",        category: "🐾 Animals & Nature" },
  { key: "SunSnow",                Icon: SunSnow,                label: "Sun Snow",          category: "🐾 Animals & Nature" },
  { key: "Moon",                   Icon: Moon,                   label: "Moon",              category: "🐾 Animals & Nature" },
  { key: "MoonStar",               Icon: MoonStar,               label: "Moon Star",         category: "🐾 Animals & Nature" },
  { key: "Sunrise",                Icon: Sunrise,                label: "Sunrise",           category: "🐾 Animals & Nature" },
  { key: "Sunset",                 Icon: Sunset,                 label: "Sunset",            category: "🐾 Animals & Nature" },
  { key: "Rainbow",                Icon: Rainbow,                label: "Rainbow",           category: "🐾 Animals & Nature" },
  { key: "Snowflake",              Icon: Snowflake,              label: "Snowflake",         category: "🐾 Animals & Nature" },
  { key: "Tornado",                Icon: Tornado,                label: "Tornado",           category: "🐾 Animals & Nature" },
  { key: "Haze",                   Icon: Haze,                   label: "Haze",              category: "🐾 Animals & Nature" },
  { key: "Wind",                   Icon: Wind,                   label: "Wind",              category: "🐾 Animals & Nature" },
  { key: "WindArrowDown",          Icon: WindArrowDown,          label: "Wind Down",         category: "🐾 Animals & Nature" },
  { key: "Cloud",                  Icon: Cloud,                  label: "Cloud",             category: "🐾 Animals & Nature" },
  { key: "CloudRain",              Icon: CloudRain,              label: "Rain",              category: "🐾 Animals & Nature" },
  { key: "CloudDrizzle",           Icon: CloudDrizzle,           label: "Drizzle",           category: "🐾 Animals & Nature" },
  { key: "CloudRainWind",          Icon: CloudRainWind,          label: "Rain & Wind",       category: "🐾 Animals & Nature" },
  { key: "CloudLightning",         Icon: CloudLightning,         label: "Lightning",         category: "🐾 Animals & Nature" },
  { key: "CloudSnow",              Icon: CloudSnow,              label: "Snow",              category: "🐾 Animals & Nature" },
  { key: "CloudHail",              Icon: CloudHail,              label: "Hail",              category: "🐾 Animals & Nature" },
  { key: "CloudFog",               Icon: CloudFog,               label: "Fog",               category: "🐾 Animals & Nature" },
  { key: "CloudSun",               Icon: CloudSun,               label: "Partly Sunny",      category: "🐾 Animals & Nature" },
  { key: "CloudSunRain",           Icon: CloudSunRain,           label: "Sun Rain",          category: "🐾 Animals & Nature" },
  { key: "CloudMoon",              Icon: CloudMoon,              label: "Cloudy Night",      category: "🐾 Animals & Nature" },
  { key: "CloudMoonRain",          Icon: CloudMoonRain,          label: "Night Rain",        category: "🐾 Animals & Nature" },
  { key: "CloudAlert",             Icon: CloudAlert,             label: "Cloud Alert",       category: "🐾 Animals & Nature" },
  { key: "CloudCheck",             Icon: CloudCheck,             label: "Cloud Check",       category: "🐾 Animals & Nature" },
  { key: "CloudCog",               Icon: CloudCog,               label: "Cloud Cog",         category: "🐾 Animals & Nature" },
  { key: "CloudOff",               Icon: CloudOff,               label: "Cloud Off",         category: "🐾 Animals & Nature" },
  { key: "CloudDownload",          Icon: CloudDownload,          label: "Cloud Download",    category: "🐾 Animals & Nature" },
  { key: "CloudUpload",            Icon: CloudUpload,            label: "Cloud Upload",      category: "🐾 Animals & Nature" },
  { key: "Droplet",                Icon: Droplet,                label: "Droplet",           category: "🐾 Animals & Nature" },
  { key: "Droplets",               Icon: Droplets,               label: "Droplets",          category: "🐾 Animals & Nature" },
  { key: "Waves",                  Icon: Waves,                  label: "Waves",             category: "🐾 Animals & Nature" },
  { key: "Mountain",               Icon: Mountain,               label: "Mountain",          category: "🐾 Animals & Nature" },
  { key: "MountainSnow",           Icon: MountainSnow,           label: "Snowy Mountain",    category: "🐾 Animals & Nature" },

  // ─── People & Emotions ─────────────────────────────────────────────────────
  { key: "User",                   Icon: User,                   label: "User",              category: "👤 People & Emotions" },
  { key: "UserCheck",              Icon: UserCheck,              label: "User Check",        category: "👤 People & Emotions" },
  { key: "UserMinus",              Icon: UserMinus,              label: "User Minus",        category: "👤 People & Emotions" },
  { key: "UserPlus",               Icon: UserPlus,               label: "User Plus",         category: "👤 People & Emotions" },
  { key: "UserX",                  Icon: UserX,                  label: "User X",            category: "👤 People & Emotions" },
  { key: "Users",                  Icon: Users,                  label: "Users",             category: "👤 People & Emotions" },
  { key: "Heart",                  Icon: Heart,                  label: "Heart",             category: "👤 People & Emotions" },
  { key: "HeartCrack",             Icon: HeartCrack,             label: "Broken Heart",      category: "👤 People & Emotions" },
  { key: "HeartHandshake",         Icon: HeartHandshake,         label: "Heart Shake",       category: "👤 People & Emotions" },
  { key: "HeartOff",               Icon: HeartOff,               label: "Heart Off",         category: "👤 People & Emotions" },
  { key: "HeartPulse",             Icon: HeartPulse,             label: "Heart Pulse",       category: "👤 People & Emotions" },
  { key: "Smile",                  Icon: Smile,                  label: "Smile",             category: "👤 People & Emotions" },
  { key: "Frown",                  Icon: Frown,                  label: "Frown",             category: "👤 People & Emotions" },
  { key: "Meh",                    Icon: Meh,                    label: "Meh",               category: "👤 People & Emotions" },
  { key: "Laugh",                  Icon: Laugh,                  label: "Laugh",             category: "👤 People & Emotions" },
  { key: "ThumbsUp",               Icon: ThumbsUp,               label: "Thumbs Up",         category: "👤 People & Emotions" },
  { key: "ThumbsDown",             Icon: ThumbsDown,             label: "Thumbs Down",       category: "👤 People & Emotions" },
  { key: "Baby",                   Icon: Baby,                   label: "Baby",              category: "👤 People & Emotions" },
  { key: "Ghost",                  Icon: Ghost,                  label: "Ghost",             category: "👤 People & Emotions" },
  { key: "Skull",                  Icon: Skull,                  label: "Skull",             category: "👤 People & Emotions" },
  { key: "PersonStanding",         Icon: PersonStanding,         label: "Person",            category: "👤 People & Emotions" },
  { key: "HandCoins",              Icon: HandCoins,              label: "Hand Coins",        category: "👤 People & Emotions" },
  { key: "Brain",                  Icon: Brain,                  label: "Brain",             category: "👤 People & Emotions" },
  { key: "BrainCircuit",           Icon: BrainCircuit,           label: "Brain Circuit",     category: "👤 People & Emotions" },
  { key: "BrainCog",               Icon: BrainCog,               label: "Brain Cog",         category: "👤 People & Emotions" },
  { key: "Bone",                   Icon: Bone,                   label: "Bone",              category: "👤 People & Emotions" },
  { key: "Dna",                    Icon: Dna,                    label: "DNA",               category: "👤 People & Emotions" },
  { key: "DnaOff",                 Icon: DnaOff,                 label: "DNA Off",           category: "👤 People & Emotions" },
  { key: "Bandage",                Icon: Bandage,                label: "Bandage",           category: "👤 People & Emotions" },
  { key: "Hand",                   Icon: Hand,                   label: "Hand",              category: "👤 People & Emotions" },
  { key: "HandFist",               Icon: HandFist,               label: "Fist",              category: "👤 People & Emotions" },
  { key: "HandGrab",               Icon: HandGrab,               label: "Hand Grab",         category: "👤 People & Emotions" },
  { key: "HandHeart",              Icon: HandHeart,              label: "Hand Heart",        category: "👤 People & Emotions" },
  { key: "HandHelping",            Icon: HandHelping,            label: "Helping Hand",      category: "👤 People & Emotions" },
  { key: "HandMetal",              Icon: HandMetal,              label: "Rock On",           category: "👤 People & Emotions" },
  { key: "HandPlatter",            Icon: HandPlatter,            label: "Hand Platter",      category: "👤 People & Emotions" },
  { key: "Handshake",              Icon: Handshake,              label: "Handshake",         category: "👤 People & Emotions" },
  { key: "Ear",                    Icon: Ear,                    label: "Ear",               category: "👤 People & Emotions" },
  { key: "EarOff",                 Icon: EarOff,                 label: "Ear Off",           category: "👤 People & Emotions" },
  { key: "EyeClosed",              Icon: EyeClosed,              label: "Eye Closed",        category: "👤 People & Emotions" },
  { key: "Armchair",               Icon: Armchair,               label: "Armchair",          category: "👤 People & Emotions" },
  { key: "Ambulance",              Icon: Ambulance,              label: "Ambulance",         category: "👤 People & Emotions" },
  { key: "Stethoscope",            Icon: Stethoscope,            label: "Stethoscope",       category: "👤 People & Emotions" },
  { key: "Pill",                   Icon: Pill,                   label: "Pill",              category: "👤 People & Emotions" },
  { key: "PillBottle",             Icon: PillBottle,             label: "Pill Bottle",       category: "👤 People & Emotions" },
  { key: "Syringe",                Icon: Syringe,                label: "Syringe",           category: "👤 People & Emotions" },
  { key: "Thermometer",            Icon: Thermometer,            label: "Thermometer",       category: "👤 People & Emotions" },
  { key: "ThermometerSnowflake",   Icon: ThermometerSnowflake,   label: "Thermometer Cold",  category: "👤 People & Emotions" },
  { key: "ThermometerSun",         Icon: ThermometerSun,         label: "Thermometer Hot",   category: "👤 People & Emotions" },

  // ─── Tech & Devices ────────────────────────────────────────────────────────
  { key: "Code",                   Icon: Code,                   label: "Code",              category: "⚙️ Tech & Devices" },
  { key: "Code2",                  Icon: Code2,                  label: "Code 2",            category: "⚙️ Tech & Devices" },
  { key: "Terminal",               Icon: Terminal,               label: "Terminal",          category: "⚙️ Tech & Devices" },
  { key: "Monitor",                Icon: Monitor,                label: "Monitor",           category: "⚙️ Tech & Devices" },
  { key: "MonitorCheck",           Icon: MonitorCheck,           label: "Monitor OK",        category: "⚙️ Tech & Devices" },
  { key: "MonitorCog",             Icon: MonitorCog,             label: "Monitor Cog",       category: "⚙️ Tech & Devices" },
  { key: "MonitorDot",             Icon: MonitorDot,             label: "Monitor Dot",       category: "⚙️ Tech & Devices" },
  { key: "MonitorOff",             Icon: MonitorOff,             label: "Monitor Off",       category: "⚙️ Tech & Devices" },
  { key: "MonitorPause",           Icon: MonitorPause,           label: "Monitor Pause",     category: "⚙️ Tech & Devices" },
  { key: "MonitorPlay",            Icon: MonitorPlay,            label: "Monitor Play",      category: "⚙️ Tech & Devices" },
  { key: "MonitorSmartphone",      Icon: MonitorSmartphone,      label: "Monitor Phone",     category: "⚙️ Tech & Devices" },
  { key: "MonitorStop",            Icon: MonitorStop,            label: "Monitor Stop",      category: "⚙️ Tech & Devices" },
  { key: "MonitorUp",              Icon: MonitorUp,              label: "Monitor Up",        category: "⚙️ Tech & Devices" },
  { key: "MonitorX",               Icon: MonitorX,               label: "Monitor X",         category: "⚙️ Tech & Devices" },
  { key: "Laptop",                 Icon: Laptop,                 label: "Laptop",            category: "⚙️ Tech & Devices" },
  { key: "Tablet",                 Icon: Tablet,                 label: "Tablet",            category: "⚙️ Tech & Devices" },
  { key: "Smartphone",             Icon: Smartphone,             label: "Smartphone",        category: "⚙️ Tech & Devices" },
  { key: "Tv",                     Icon: Tv,                     label: "TV",                category: "⚙️ Tech & Devices" },
  { key: "Watch",                  Icon: Watch,                  label: "Watch",             category: "⚙️ Tech & Devices" },
  { key: "Cpu",                    Icon: Cpu,                    label: "CPU",               category: "⚙️ Tech & Devices" },
  { key: "CircuitBoard",           Icon: CircuitBoard,           label: "Circuit Board",     category: "⚙️ Tech & Devices" },
  { key: "HardDrive",              Icon: HardDrive,              label: "Hard Drive",        category: "⚙️ Tech & Devices" },
  { key: "HardDriveDownload",      Icon: HardDriveDownload,      label: "HDD Download",      category: "⚙️ Tech & Devices" },
  { key: "HardDriveUpload",        Icon: HardDriveUpload,        label: "HDD Upload",        category: "⚙️ Tech & Devices" },
  { key: "Server",                 Icon: Server,                 label: "Server",            category: "⚙️ Tech & Devices" },
  { key: "ServerCog",              Icon: ServerCog,              label: "Server Cog",        category: "⚙️ Tech & Devices" },
  { key: "ServerCrash",            Icon: ServerCrash,            label: "Server Crash",      category: "⚙️ Tech & Devices" },
  { key: "ServerOff",              Icon: ServerOff,              label: "Server Off",        category: "⚙️ Tech & Devices" },
  { key: "Database",               Icon: Database,               label: "Database",          category: "⚙️ Tech & Devices" },
  { key: "DatabaseBackup",         Icon: DatabaseBackup,         label: "DB Backup",         category: "⚙️ Tech & Devices" },
  { key: "DatabaseZap",            Icon: DatabaseZap,            label: "DB Zap",            category: "⚙️ Tech & Devices" },
  { key: "Globe",                  Icon: Globe,                  label: "Globe",             category: "⚙️ Tech & Devices" },
  { key: "Wifi",                   Icon: Wifi,                   label: "Wifi",              category: "⚙️ Tech & Devices" },
  { key: "WifiOff",                Icon: WifiOff,                label: "Wifi Off",          category: "⚙️ Tech & Devices" },
  { key: "Signal",                 Icon: Signal,                 label: "Signal",            category: "⚙️ Tech & Devices" },
  { key: "SignalHigh",             Icon: SignalHigh,             label: "Signal High",       category: "⚙️ Tech & Devices" },
  { key: "Bluetooth",              Icon: Bluetooth,              label: "Bluetooth",         category: "⚙️ Tech & Devices" },
  { key: "Radio",                  Icon: Radio,                  label: "Radio",             category: "⚙️ Tech & Devices" },
  { key: "Radar",                  Icon: Radar,                  label: "Radar",             category: "⚙️ Tech & Devices" },
  { key: "Satellite",              Icon: Satellite,              label: "Satellite",         category: "⚙️ Tech & Devices" },
  { key: "SatelliteDish",          Icon: SatelliteDish,          label: "Satellite Dish",    category: "⚙️ Tech & Devices" },
  { key: "Nfc",                    Icon: Nfc,                    label: "NFC",               category: "⚙️ Tech & Devices" },
  { key: "Cable",                  Icon: Cable,                  label: "Cable",             category: "⚙️ Tech & Devices" },
  { key: "Component",              Icon: Component,              label: "Component",         category: "⚙️ Tech & Devices" },
  { key: "Plug",                   Icon: Plug,                   label: "Plug",              category: "⚙️ Tech & Devices" },
  { key: "Unplug",                 Icon: Unplug,                 label: "Unplug",            category: "⚙️ Tech & Devices" },
  { key: "Printer",                Icon: Printer,                label: "Printer",           category: "⚙️ Tech & Devices" },
  { key: "PrinterCheck",           Icon: PrinterCheck,           label: "Printer OK",        category: "⚙️ Tech & Devices" },
  { key: "Camera",                 Icon: Camera,                 label: "Camera",            category: "⚙️ Tech & Devices" },
  { key: "Video",                  Icon: Video,                  label: "Video",             category: "⚙️ Tech & Devices" },
  { key: "Image",                  Icon: Image,                  label: "Image",             category: "⚙️ Tech & Devices" },
  { key: "Mic",                    Icon: Mic,                    label: "Mic",               category: "⚙️ Tech & Devices" },
  { key: "MicOff",                 Icon: MicOff,                 label: "Mic Off",           category: "⚙️ Tech & Devices" },
  { key: "Speaker",                Icon: Speaker,                label: "Speaker",           category: "⚙️ Tech & Devices" },
  { key: "Volume",                 Icon: Volume,                 label: "Volume",            category: "⚙️ Tech & Devices" },
  { key: "Volume1",                Icon: Volume1,                label: "Volume 1",          category: "⚙️ Tech & Devices" },
  { key: "Volume2",                Icon: Volume2,                label: "Volume 2",          category: "⚙️ Tech & Devices" },
  { key: "VolumeX",                Icon: VolumeX,                label: "Mute",              category: "⚙️ Tech & Devices" },
  { key: "Headphones",             Icon: Headphones,             label: "Headphones",        category: "⚙️ Tech & Devices" },
  { key: "Keyboard",               Icon: Keyboard,               label: "Keyboard",          category: "⚙️ Tech & Devices" },
  { key: "Mouse",                  Icon: Mouse,                  label: "Mouse",             category: "⚙️ Tech & Devices" },
  { key: "Power",                  Icon: Power,                  label: "Power",             category: "⚙️ Tech & Devices" },
  { key: "Binary",                 Icon: Binary,                 label: "Binary",            category: "⚙️ Tech & Devices" },
  { key: "Network",                Icon: Network,                label: "Network",           category: "⚙️ Tech & Devices" },
  { key: "Layers",                 Icon: Layers,                 label: "Layers",            category: "⚙️ Tech & Devices" },
  { key: "ScanBarcode",            Icon: ScanBarcode,            label: "Scan Barcode",      category: "⚙️ Tech & Devices" },
  { key: "ScanEye",                Icon: ScanEye,                label: "Scan Eye",          category: "⚙️ Tech & Devices" },
  { key: "ScanFace",               Icon: ScanFace,               label: "Face Scan",         category: "⚙️ Tech & Devices" },
  { key: "ScanHeart",              Icon: ScanHeart,              label: "Scan Heart",        category: "⚙️ Tech & Devices" },
  { key: "ScanLine",               Icon: ScanLine,               label: "Scan Line",         category: "⚙️ Tech & Devices" },
  { key: "ScanSearch",             Icon: ScanSearch,             label: "Scan Search",       category: "⚙️ Tech & Devices" },
  { key: "ScanText",               Icon: ScanText,               label: "Scan Text",         category: "⚙️ Tech & Devices" },
  { key: "BotMessageSquare",       Icon: BotMessageSquare,       label: "Bot Message",       category: "⚙️ Tech & Devices" },
  { key: "BotOff",                 Icon: BotOff,                 label: "Bot Off",           category: "⚙️ Tech & Devices" },

  // ─── Security & Safety ─────────────────────────────────────────────────────
  { key: "Shield",                 Icon: Shield,                 label: "Shield",            category: "🔒 Security & Safety" },
  { key: "ShieldCheck",            Icon: ShieldCheck,            label: "Shield Check",      category: "🔒 Security & Safety" },
  { key: "ShieldAlert",            Icon: ShieldAlert,            label: "Shield Alert",      category: "🔒 Security & Safety" },
  { key: "ShieldOff",              Icon: ShieldOff,              label: "Shield Off",        category: "🔒 Security & Safety" },
  { key: "ShieldX",                Icon: ShieldX,                label: "Shield X",          category: "🔒 Security & Safety" },
  { key: "Lock",                   Icon: Lock,                   label: "Lock",              category: "🔒 Security & Safety" },
  { key: "LockOpen",               Icon: LockOpen,               label: "Unlocked",          category: "🔒 Security & Safety" },
  { key: "LockKeyhole",            Icon: LockKeyhole,            label: "Keyhole Lock",      category: "🔒 Security & Safety" },
  { key: "Key",                    Icon: Key,                    label: "Key",               category: "🔒 Security & Safety" },
  { key: "KeyRound",               Icon: KeyRound,               label: "Key Round",         category: "🔒 Security & Safety" },
  { key: "Eye",                    Icon: Eye,                    label: "Eye",               category: "🔒 Security & Safety" },
  { key: "EyeOff",                 Icon: EyeOff,                 label: "Eye Off",           category: "🔒 Security & Safety" },
  { key: "Fingerprint",            Icon: Fingerprint,            label: "Fingerprint",       category: "🔒 Security & Safety" },
  { key: "TriangleAlert",          Icon: TriangleAlert,          label: "Alert",             category: "🔒 Security & Safety" },
  { key: "CircleAlert",            Icon: CircleAlert,            label: "Alert Circle",      category: "🔒 Security & Safety" },
  { key: "OctagonAlert",           Icon: OctagonAlert,           label: "Alert Stop",        category: "🔒 Security & Safety" },
  { key: "Scan",                   Icon: Scan,                   label: "Scan",              category: "🔒 Security & Safety" },
  { key: "QrCode",                 Icon: QrCode,                 label: "QR Code",           category: "🔒 Security & Safety" },

  // ─── Finance & Trade ───────────────────────────────────────────────────────
  { key: "DollarSign",             Icon: DollarSign,             label: "Dollar",            category: "💰 Finance & Trade" },
  { key: "Euro",                   Icon: Euro,                   label: "Euro",              category: "💰 Finance & Trade" },
  { key: "Bitcoin",                Icon: Bitcoin,                label: "Bitcoin",           category: "💰 Finance & Trade" },
  { key: "CreditCard",             Icon: CreditCard,             label: "Credit Card",       category: "💰 Finance & Trade" },
  { key: "Wallet",                 Icon: Wallet,                 label: "Wallet",            category: "💰 Finance & Trade" },
  { key: "Coins",                  Icon: Coins,                  label: "Coins",             category: "💰 Finance & Trade" },
  { key: "Banknote",               Icon: Banknote,               label: "Banknote",          category: "💰 Finance & Trade" },
  { key: "Receipt",                Icon: Receipt,                label: "Receipt",           category: "💰 Finance & Trade" },
  { key: "ShoppingCart",           Icon: ShoppingCart,           label: "Cart",              category: "💰 Finance & Trade" },
  { key: "ShoppingBag",            Icon: ShoppingBag,            label: "Shopping Bag",      category: "💰 Finance & Trade" },
  { key: "Store",                  Icon: Store,                  label: "Store",             category: "💰 Finance & Trade" },
  { key: "Package",                Icon: Package,                label: "Package",           category: "💰 Finance & Trade" },
  { key: "Tag",                    Icon: Tag,                    label: "Tag",               category: "💰 Finance & Trade" },
  { key: "Tags",                   Icon: Tags,                   label: "Tags",              category: "💰 Finance & Trade" },
  { key: "Percent",                Icon: Percent,                label: "Percent",           category: "💰 Finance & Trade" },
  { key: "Scale",                  Icon: Scale,                  label: "Scale",             category: "💰 Finance & Trade" },
  { key: "Calculator",             Icon: Calculator,             label: "Calculator",        category: "💰 Finance & Trade" },
  { key: "PieChart",               Icon: PieChart,               label: "Pie Chart",         category: "💰 Finance & Trade" },

  // ─── Communication ─────────────────────────────────────────────────────────
  { key: "MessageCircle",          Icon: MessageCircle,          label: "Message",           category: "💬 Communication" },
  { key: "MessageSquare",          Icon: MessageSquare,          label: "Message Sq",        category: "💬 Communication" },
  { key: "Mail",                   Icon: Mail,                   label: "Mail",              category: "💬 Communication" },
  { key: "MailOpen",               Icon: MailOpen,               label: "Mail Open",         category: "💬 Communication" },
  { key: "Phone",                  Icon: Phone,                  label: "Phone",             category: "💬 Communication" },
  { key: "PhoneCall",              Icon: PhoneCall,              label: "Phone Call",        category: "💬 Communication" },
  { key: "PhoneIncoming",          Icon: PhoneIncoming,          label: "Incoming",          category: "💬 Communication" },
  { key: "PhoneOutgoing",          Icon: PhoneOutgoing,          label: "Outgoing",          category: "💬 Communication" },
  { key: "PhoneMissed",            Icon: PhoneMissed,            label: "Missed Call",       category: "💬 Communication" },
  { key: "PhoneOff",               Icon: PhoneOff,               label: "Phone Off",         category: "💬 Communication" },
  { key: "Send",                   Icon: Send,                   label: "Send",              category: "💬 Communication" },
  { key: "Megaphone",              Icon: Megaphone,              label: "Megaphone",         category: "💬 Communication" },
  { key: "Bell",                   Icon: Bell,                   label: "Bell",              category: "💬 Communication" },
  { key: "BellDot",                Icon: BellDot,                label: "Bell Dot",          category: "💬 Communication" },
  { key: "BellOff",                Icon: BellOff,                label: "Bell Off",          category: "💬 Communication" },
  { key: "BellPlus",               Icon: BellPlus,               label: "Bell Plus",         category: "💬 Communication" },
  { key: "BellRing",               Icon: BellRing,               label: "Bell Ring",         category: "💬 Communication" },
  { key: "Share",                  Icon: Share,                  label: "Share",             category: "💬 Communication" },
  { key: "Share2",                 Icon: Share2,                 label: "Share 2",           category: "💬 Communication" },
  { key: "Link",                   Icon: Link,                   label: "Link",              category: "💬 Communication" },
  { key: "Link2",                  Icon: Link2,                  label: "Link 2",            category: "💬 Communication" },
  { key: "ExternalLink",           Icon: ExternalLink,           label: "External Link",     category: "💬 Communication" },
  { key: "Rss",                    Icon: Rss,                    label: "RSS",               category: "💬 Communication" },
  { key: "Podcast",                Icon: Podcast,                label: "Podcast",           category: "💬 Communication" },
  { key: "Forward",                Icon: Forward,                label: "Forward",           category: "💬 Communication" },
  { key: "Reply",                  Icon: Reply,                  label: "Reply",             category: "💬 Communication" },

  // ─── Media & Entertainment ─────────────────────────────────────────────────
  { key: "Play",                   Icon: Play,                   label: "Play",              category: "🎬 Media & Entertainment" },
  { key: "Pause",                  Icon: Pause,                  label: "Pause",             category: "🎬 Media & Entertainment" },
  { key: "Music",                  Icon: Music,                  label: "Music",             category: "🎬 Media & Entertainment" },
  { key: "Music2",                 Icon: Music2,                 label: "Music Note",        category: "🎬 Media & Entertainment" },
  { key: "Film",                   Icon: Film,                   label: "Film",              category: "🎬 Media & Entertainment" },
  { key: "Clapperboard",           Icon: Clapperboard,           label: "Clapperboard",      category: "🎬 Media & Entertainment" },
  { key: "Disc",                   Icon: Disc,                   label: "Disc",              category: "🎬 Media & Entertainment" },
  { key: "BookOpen",               Icon: BookOpen,               label: "Book Open",         category: "🎬 Media & Entertainment" },
  { key: "Book",                   Icon: Book,                   label: "Book",              category: "🎬 Media & Entertainment" },
  { key: "BookMarked",             Icon: BookMarked,             label: "Bookmarked",        category: "🎬 Media & Entertainment" },
  { key: "ScrollText",             Icon: ScrollText,             label: "Scroll Text",       category: "🎬 Media & Entertainment" },
  { key: "Gamepad2",               Icon: Gamepad2,               label: "Gamepad",           category: "🎬 Media & Entertainment" },
  { key: "Joystick",               Icon: Joystick,               label: "Joystick",          category: "🎬 Media & Entertainment" },

  // ─── Sports & Action ───────────────────────────────────────────────────────
  { key: "Dumbbell",               Icon: Dumbbell,               label: "Dumbbell",          category: "🏋️ Sports & Action" },
  { key: "Weight",                 Icon: Weight,                 label: "Weight",            category: "🏋️ Sports & Action" },
  { key: "Volleyball",             Icon: Volleyball,             label: "Volleyball",        category: "🏋️ Sports & Action" },
  { key: "Kayak",                  Icon: Kayak,                  label: "Kayak",             category: "🏋️ Sports & Action" },
  { key: "Target",                 Icon: Target,                 label: "Target",            category: "🏋️ Sports & Action" },
  { key: "Crosshair",              Icon: Crosshair,              label: "Crosshair",         category: "🏋️ Sports & Action" },
  { key: "Swords",                 Icon: Swords,                 label: "Swords",            category: "🏋️ Sports & Action" },
  { key: "Sword",                  Icon: Sword,                  label: "Sword",             category: "🏋️ Sports & Action" },
  { key: "Axe",                    Icon: Axe,                    label: "Axe",               category: "🏋️ Sports & Action" },
  { key: "Bomb",                   Icon: Bomb,                   label: "Bomb",              category: "🏋️ Sports & Action" },
  { key: "Flag",                   Icon: Flag,                   label: "Flag",              category: "🏋️ Sports & Action" },
  { key: "FlagOff",                Icon: FlagOff,                label: "Flag Off",          category: "🏋️ Sports & Action" },
  { key: "Move",                   Icon: Move,                   label: "Move",              category: "🏋️ Sports & Action" },
  { key: "MoveRight",              Icon: MoveRight,              label: "Move Right",        category: "🏋️ Sports & Action" },
  { key: "MoveLeft",               Icon: MoveLeft,               label: "Move Left",         category: "🏋️ Sports & Action" },
  { key: "MoveUp",                 Icon: MoveUp,                 label: "Move Up",           category: "🏋️ Sports & Action" },
  { key: "MoveDown",               Icon: MoveDown,               label: "Move Down",         category: "🏋️ Sports & Action" },
  { key: "Navigation",             Icon: Navigation,             label: "Navigation",        category: "🏋️ Sports & Action" },
  { key: "Navigation2",            Icon: Navigation2,            label: "Navigation 2",      category: "🏋️ Sports & Action" },
  { key: "Compass",                Icon: Compass,                label: "Compass",           category: "🏋️ Sports & Action" },

  // ─── Symbols & Signs ───────────────────────────────────────────────────────
  { key: "Infinity",               Icon: Infinity,               label: "Infinity",          category: "🔣 Symbols & Signs" },
  { key: "Hash",                   Icon: Hash,                   label: "Hash",              category: "🔣 Symbols & Signs" },
  { key: "AtSign",                 Icon: AtSign,                 label: "At Sign",           category: "🔣 Symbols & Signs" },
  { key: "Asterisk",               Icon: Asterisk,               label: "Asterisk",          category: "🔣 Symbols & Signs" },
  { key: "Plus",                   Icon: Plus,                   label: "Plus",              category: "🔣 Symbols & Signs" },
  { key: "Minus",                  Icon: Minus,                  label: "Minus",             category: "🔣 Symbols & Signs" },
  { key: "Divide",                 Icon: Divide,                 label: "Divide",            category: "🔣 Symbols & Signs" },
  { key: "CircleCheck",            Icon: CircleCheck,            label: "Check Circle",      category: "🔣 Symbols & Signs" },
  { key: "CircleCheckBig",         Icon: CircleCheckBig,         label: "Check Circle 2",    category: "🔣 Symbols & Signs" },
  { key: "CircleX",                Icon: CircleX,                label: "X Circle",          category: "🔣 Symbols & Signs" },
  { key: "Circle",                 Icon: Circle,                 label: "Circle",            category: "🔣 Symbols & Signs" },
  { key: "CircleDot",              Icon: CircleDot,              label: "Circle Dot",        category: "🔣 Symbols & Signs" },
  { key: "CirclePlus",             Icon: CirclePlus,             label: "Circle Plus",       category: "🔣 Symbols & Signs" },
  { key: "CircleMinus",            Icon: CircleMinus,            label: "Circle Minus",      category: "🔣 Symbols & Signs" },
  { key: "Triangle",               Icon: Triangle,               label: "Triangle",          category: "🔣 Symbols & Signs" },
  { key: "Square",                 Icon: Square,                 label: "Square",            category: "🔣 Symbols & Signs" },
  { key: "Info",                   Icon: Info,                   label: "Info",              category: "🔣 Symbols & Signs" },
  { key: "Ban",                    Icon: Ban,                    label: "Ban",               category: "🔣 Symbols & Signs" },
  { key: "Slash",                  Icon: Slash,                  label: "Slash",             category: "🔣 Symbols & Signs" },
  { key: "Copyright",              Icon: Copyright,              label: "Copyright",         category: "🔣 Symbols & Signs" },
  { key: "ChevronRight",           Icon: ChevronRight,           label: "Chevron Right",     category: "🔣 Symbols & Signs" },
  { key: "ChevronLeft",            Icon: ChevronLeft,            label: "Chevron Left",      category: "🔣 Symbols & Signs" },
  { key: "ChevronUp",              Icon: ChevronUp,              label: "Chevron Up",        category: "🔣 Symbols & Signs" },
  { key: "ChevronDown",            Icon: ChevronDown,            label: "Chevron Down",      category: "🔣 Symbols & Signs" },

  // ─── World & Places ────────────────────────────────────────────────────────
  { key: "Map",                    Icon: MapIcon,                label: "Map",               category: "🌍 World & Places" },
  { key: "MapPin",                 Icon: MapPin,                 label: "Map Pin",           category: "🌍 World & Places" },
  { key: "Landmark",               Icon: Landmark,               label: "Landmark",          category: "🌍 World & Places" },
  { key: "Home",                   Icon: Home,                   label: "Home",              category: "🌍 World & Places" },
  { key: "Building",               Icon: Building,               label: "Building",          category: "🌍 World & Places" },
  { key: "Building2",              Icon: Building2,              label: "Building 2",        category: "🌍 World & Places" },
  { key: "Hotel",                  Icon: Hotel,                  label: "Hotel",             category: "🌍 World & Places" },
  { key: "School",                 Icon: School,                 label: "School",            category: "🌍 World & Places" },
  { key: "Hospital",               Icon: Hospital,               label: "Hospital",          category: "🌍 World & Places" },
  { key: "Plane",                  Icon: Plane,                  label: "Plane",             category: "🌍 World & Places" },
  { key: "Car",                    Icon: Car,                    label: "Car",               category: "🌍 World & Places" },
  { key: "Truck",                  Icon: Truck,                  label: "Truck",             category: "🌍 World & Places" },
  { key: "Bike",                   Icon: Bike,                   label: "Bike",              category: "🌍 World & Places" },
  { key: "Ship",                   Icon: Ship,                   label: "Ship",              category: "🌍 World & Places" },
  { key: "Train",                  Icon: TrainFront,             label: "Train",             category: "🌍 World & Places" },
  { key: "Bus",                    Icon: Bus,                    label: "Bus",               category: "🌍 World & Places" },
  { key: "Sailboat",               Icon: Sailboat,               label: "Sailboat",          category: "🌍 World & Places" },
  { key: "Tent",                   Icon: Tent,                   label: "Tent",              category: "🌍 World & Places" },
  { key: "Castle",                 Icon: Castle,                 label: "Castle",            category: "🌍 World & Places" },

  // ─── Food & Life ───────────────────────────────────────────────────────────
  { key: "Coffee",                 Icon: Coffee,                 label: "Coffee",            category: "🍕 Food & Life" },
  { key: "Beer",                   Icon: Beer,                   label: "Beer",              category: "🍕 Food & Life" },
  { key: "Wine",                   Icon: Wine,                   label: "Wine",              category: "🍕 Food & Life" },
  { key: "Pizza",                  Icon: Pizza,                  label: "Pizza",             category: "🍕 Food & Life" },
  { key: "Apple",                  Icon: Apple,                  label: "Apple",             category: "🍕 Food & Life" },
  { key: "Cherry",                 Icon: Cherry,                 label: "Cherry",            category: "🍕 Food & Life" },
  { key: "Banana",                 Icon: Banana,                 label: "Banana",            category: "🍕 Food & Life" },
  { key: "Grape",                  Icon: Grape,                  label: "Grapes",            category: "🍕 Food & Life" },
  { key: "Carrot",                 Icon: Carrot,                 label: "Carrot",            category: "🍕 Food & Life" },
  { key: "Bean",                   Icon: Bean,                   label: "Bean",              category: "🍕 Food & Life" },
  { key: "BeanOff",                Icon: BeanOff,                label: "Bean Off",          category: "🍕 Food & Life" },
  { key: "Nut",                    Icon: Nut,                    label: "Nut",               category: "🍕 Food & Life" },
  { key: "NutOff",                 Icon: NutOff,                 label: "Nut Off",           category: "🍕 Food & Life" },
  { key: "IceCreamCone",           Icon: IceCreamCone,           label: "Ice Cream",         category: "🍕 Food & Life" },
  { key: "Donut",                  Icon: Donut,                  label: "Donut",             category: "🍕 Food & Life" },
  { key: "EggFried",               Icon: EggFried,               label: "Fried Egg",         category: "🍕 Food & Life" },
  { key: "Lollipop",               Icon: Lollipop,               label: "Lollipop",          category: "🍕 Food & Life" },
  { key: "Popsicle",               Icon: Popsicle,               label: "Popsicle",          category: "🍕 Food & Life" },
  { key: "Cookie",                 Icon: Cookie,                 label: "Cookie",            category: "🍕 Food & Life" },
  { key: "Cake",                   Icon: Cake,                   label: "Cake",              category: "🍕 Food & Life" },
  { key: "Croissant",              Icon: Croissant,              label: "Croissant",         category: "🍕 Food & Life" },
  { key: "Sandwich",               Icon: Sandwich,               label: "Sandwich",          category: "🍕 Food & Life" },
  { key: "Soup",                   Icon: Soup,                   label: "Soup",              category: "🍕 Food & Life" },
  { key: "Salad",                  Icon: Salad,                  label: "Salad",             category: "🍕 Food & Life" },
  { key: "ChefHat",                Icon: ChefHat,                label: "Chef Hat",          category: "🍕 Food & Life" },
  { key: "UtensilsCrossed",        Icon: UtensilsCrossed,        label: "Utensils X",        category: "🍕 Food & Life" },
  { key: "Utensils",               Icon: Utensils,               label: "Utensils",          category: "🍕 Food & Life" },
  { key: "CookingPot",             Icon: CookingPot,             label: "Cooking Pot",       category: "🍕 Food & Life" },
  { key: "Microwave",              Icon: Microwave,              label: "Microwave",         category: "🍕 Food & Life" },
  { key: "Refrigerator",           Icon: Refrigerator,           label: "Fridge",            category: "🍕 Food & Life" },
  { key: "Gift",                   Icon: Gift,                   label: "Gift",              category: "🍕 Food & Life" },
  { key: "PartyPopper",            Icon: PartyPopper,            label: "Party",             category: "🍕 Food & Life" },
  { key: "Anchor",                 Icon: Anchor,                 label: "Anchor",            category: "🍕 Food & Life" },
  { key: "Hourglass",              Icon: Hourglass,              label: "Hourglass",         category: "🍕 Food & Life" },
  { key: "Umbrella",               Icon: Umbrella,               label: "Umbrella",          category: "🍕 Food & Life" },
  { key: "Magnet",                 Icon: Magnet,                 label: "Magnet",            category: "🍕 Food & Life" },
  { key: "Lightbulb",              Icon: Lightbulb,              label: "Lightbulb",         category: "🍕 Food & Life" },
  { key: "LightbulbOff",           Icon: LightbulbOff,           label: "Light Off",         category: "🍕 Food & Life" },

  // ─── Design & Tools ────────────────────────────────────────────────────────
  { key: "Palette",                Icon: Palette,                label: "Palette",           category: "🎨 Design & Tools" },
  { key: "Paintbrush",             Icon: Paintbrush,             label: "Paintbrush",        category: "🎨 Design & Tools" },
  { key: "Eraser",                 Icon: Eraser,                 label: "Eraser",            category: "🎨 Design & Tools" },
  { key: "Pencil",                 Icon: Pencil,                 label: "Pencil",            category: "🎨 Design & Tools" },
  { key: "Pen",                    Icon: Pen,                    label: "Pen",               category: "🎨 Design & Tools" },
  { key: "PenLine",                Icon: PenLine,                label: "Pen Line",          category: "🎨 Design & Tools" },
  { key: "Highlighter",            Icon: Highlighter,            label: "Highlighter",       category: "🎨 Design & Tools" },
  { key: "Scissors",               Icon: Scissors,               label: "Scissors",          category: "🎨 Design & Tools" },
  { key: "Crop",                   Icon: Crop,                   label: "Crop",              category: "🎨 Design & Tools" },
  { key: "Wand",                   Icon: Wand,                   label: "Wand",              category: "🎨 Design & Tools" },
  { key: "Blend",                  Icon: Blend,                  label: "Blend",             category: "🎨 Design & Tools" },
  { key: "Blocks",                 Icon: Blocks,                 label: "Blocks",            category: "🎨 Design & Tools" },
  { key: "Wrench",                 Icon: Wrench,                 label: "Wrench",            category: "🎨 Design & Tools" },
  { key: "Hammer",                 Icon: Hammer,                 label: "Hammer",            category: "🎨 Design & Tools" },
  { key: "Cog",                    Icon: Cog,                    label: "Cog",               category: "🎨 Design & Tools" },
  { key: "Settings",               Icon: Settings,               label: "Settings",          category: "🎨 Design & Tools" },
  { key: "Settings2",              Icon: Settings2,              label: "Settings 2",        category: "🎨 Design & Tools" },
  { key: "SlidersHorizontal",      Icon: SlidersHorizontal,      label: "Sliders H",         category: "🎨 Design & Tools" },
  { key: "SlidersVertical",        Icon: SlidersVertical,        label: "Sliders V",         category: "🎨 Design & Tools" },
  { key: "FlaskConical",           Icon: FlaskConical,           label: "Flask",             category: "🎨 Design & Tools" },
  { key: "TestTube",               Icon: TestTube,               label: "Test Tube",         category: "🎨 Design & Tools" },
  { key: "Atom",                   Icon: Atom,                   label: "Atom",              category: "🎨 Design & Tools" },
  { key: "Microscope",             Icon: Microscope,             label: "Microscope",        category: "🎨 Design & Tools" },
  { key: "Telescope",              Icon: Telescope,              label: "Telescope",         category: "🎨 Design & Tools" },
  { key: "Binoculars",             Icon: Binoculars,             label: "Binoculars",        category: "🎨 Design & Tools" },
  { key: "Bookmark",               Icon: Bookmark,               label: "Bookmark",          category: "🎨 Design & Tools" },
  { key: "BookmarkPlus",           Icon: BookmarkPlus,           label: "Bookmark +",        category: "🎨 Design & Tools" },
  { key: "BookmarkCheck",          Icon: BookmarkCheck,          label: "Bookmark ✓",        category: "🎨 Design & Tools" },
  { key: "BookmarkX",              Icon: BookmarkX,              label: "Bookmark X",        category: "🎨 Design & Tools" },
  { key: "Paperclip",              Icon: Paperclip,              label: "Paperclip",         category: "🎨 Design & Tools" },
  { key: "Pin",                    Icon: Pin,                    label: "Pin",               category: "🎨 Design & Tools" },
  { key: "PinOff",                 Icon: PinOff,                 label: "Pin Off",           category: "🎨 Design & Tools" },
];

const _keyMap = new Map<string, LucideIcon>(
  ICON_REGISTRY.map(e => [e.key, e.Icon])
);

export function getIconByKey(key: string): LucideIcon | null {
  return _keyMap.get(key) ?? null;
}
